export const DELTA_SCHEMA_VERSION = "0.3.1";

export const DELTA_SCHEMA_SQL = [
  `CREATE TABLE IF NOT EXISTS delta_meta (
    key text PRIMARY KEY,
    value text NOT NULL,
    updated_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS actors (
    id text PRIMARY KEY,
    kind text NOT NULL,
    name text,
    metadata_json text,
    created_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS sessions (
    id text PRIMARY KEY,
    workspace_root text NOT NULL,
    source text NOT NULL,
    branch text,
    started_at text NOT NULL,
    ended_at text,
    summary text,
    metadata_json text
  )`,
  `CREATE TABLE IF NOT EXISTS operations (
    id text PRIMARY KEY,
    session_id text,
    txn_id text,
    kind text NOT NULL,
    timestamp text NOT NULL,
    actor_id text,
    summary text,
    data_json text NOT NULL,
    redaction_json text,
    hash text,
    prev_hash text
  )`,
  `CREATE TABLE IF NOT EXISTS file_changes (
    id text PRIMARY KEY,
    operation_id text NOT NULL,
    path text NOT NULL,
    change_type text NOT NULL,
    hash_before text,
    hash_after text,
    diff_summary text,
    semantic_hints_json text
  )`,
  `CREATE TABLE IF NOT EXISTS command_runs (
    id text PRIMARY KEY,
    operation_id text NOT NULL,
    command_name text NOT NULL,
    argv_redacted_json text,
    exit_code integer,
    duration_ms integer,
    diagnostics_json text
  )`,
  `CREATE TABLE IF NOT EXISTS proofs (
    id text PRIMARY KEY,
    operation_id text NOT NULL,
    proof_kind text NOT NULL,
    command text,
    result text NOT NULL,
    assurance text,
    diagnostics_json text,
    artifact_paths_json text
  )`,
  `CREATE TABLE IF NOT EXISTS runtime_calls (
    id text PRIMARY KEY,
    operation_id text NOT NULL,
    entry_name text NOT NULL,
    entry_kind text,
    risk text,
    policy text,
    tenant_scoped integer,
    result text,
    diagnostic_code text,
    trace_id text,
    service text,
    language text,
    needs_approval integer
  )`,
  `ALTER TABLE runtime_calls ADD COLUMN IF NOT EXISTS needs_approval integer`,
  `CREATE TABLE IF NOT EXISTS artifacts (
    id text PRIMARY KEY,
    operation_id text NOT NULL,
    path text NOT NULL,
    artifact_kind text,
    hash text,
    generated integer
  )`,
  `CREATE TABLE IF NOT EXISTS git_mappings (
    id text PRIMARY KEY,
    operation_id text,
    commit_sha text,
    branch text,
    detected_at text,
    confidence real,
    metadata_json text
  )`,
  `CREATE TABLE IF NOT EXISTS work_sessions (
    id text PRIMARY KEY,
    workspace_root text NOT NULL,
    kind text NOT NULL,
    status text NOT NULL,
    title text,
    inferred_intent text,
    confidence real NOT NULL,
    started_at text NOT NULL,
    ended_at text,
    actor_ids_json text,
    git_branch text,
    git_head_start text,
    git_head_end text,
    summary text,
    metadata_json text,
    created_at text NOT NULL,
    updated_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS work_session_operations (
    work_session_id text NOT NULL,
    operation_id text NOT NULL,
    link_type text NOT NULL,
    confidence real NOT NULL,
    reason_json text,
    created_at text NOT NULL,
    PRIMARY KEY (work_session_id, operation_id)
  )`,
  `CREATE TABLE IF NOT EXISTS work_session_signals (
    id text PRIMARY KEY,
    work_session_id text,
    operation_id text,
    signal_type text NOT NULL,
    weight real NOT NULL,
    value text,
    metadata_json text,
    created_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS work_session_summaries (
    id text PRIMARY KEY,
    work_session_id text NOT NULL,
    summary_type text NOT NULL,
    content text NOT NULL,
    generated_by text,
    created_at text NOT NULL,
    redaction_json text
  )`,
  `CREATE TABLE IF NOT EXISTS timeline_events (
    id text PRIMARY KEY,
    operation_id text,
    session_id text,
    change_id text,
    timestamp text NOT NULL,
    event_kind text NOT NULL,
    title text NOT NULL,
    summary text,
    severity text,
    confidence real NOT NULL,
    data_json text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS timeline_entities (
    id text PRIMARY KEY,
    timeline_event_id text NOT NULL,
    entity_kind text NOT NULL,
    entity_name text NOT NULL,
    role text NOT NULL,
    confidence real NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS timeline_edges (
    id text PRIMARY KEY,
    from_event_id text NOT NULL,
    to_event_id text NOT NULL,
    edge_kind text NOT NULL,
    confidence real NOT NULL,
    reason_json text
  )`,
  `CREATE TABLE IF NOT EXISTS timeline_projection_state (
    id text PRIMARY KEY,
    last_operation_id text,
    last_rebuild_at text,
    projection_version text,
    graph_hash text
  )`,
  `CREATE TABLE IF NOT EXISTS agent_event_sources (
    id text PRIMARY KEY,
    source_name text NOT NULL,
    source_kind text NOT NULL,
    integration_kind text NOT NULL,
    trust_level text NOT NULL,
    config_json text,
    created_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS external_agent_events (
    id text PRIMARY KEY,
    source_id text NOT NULL,
    external_session_id text,
    external_turn_id text,
    event_kind text NOT NULL,
    captured_at text NOT NULL,
    payload_redacted_json text NOT NULL,
    payload_hash text,
    raw_stored integer DEFAULT 0,
    normalization_status text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS agent_memory_events (
    id text PRIMARY KEY,
    external_event_id text,
    forge_session_id text,
    forge_change_id text,
    operation_id text,
    normalized_kind text NOT NULL,
    summary text,
    confidence real NOT NULL,
    data_json text NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS operations_timestamp_idx ON operations(timestamp)`,
  `CREATE INDEX IF NOT EXISTS operations_kind_idx ON operations(kind)`,
  `CREATE INDEX IF NOT EXISTS operations_session_idx ON operations(session_id)`,
  `CREATE INDEX IF NOT EXISTS file_changes_path_idx ON file_changes(path)`,
  `CREATE INDEX IF NOT EXISTS runtime_calls_entry_idx ON runtime_calls(entry_name)`,
  `CREATE INDEX IF NOT EXISTS artifacts_path_idx ON artifacts(path)`,
  `CREATE INDEX IF NOT EXISTS work_sessions_status_idx ON work_sessions(status, updated_at)`,
  `CREATE INDEX IF NOT EXISTS work_sessions_branch_idx ON work_sessions(git_branch)`,
  `CREATE INDEX IF NOT EXISTS work_session_operations_operation_idx ON work_session_operations(operation_id)`,
  `CREATE INDEX IF NOT EXISTS work_session_signals_session_idx ON work_session_signals(work_session_id)`,
  `CREATE INDEX IF NOT EXISTS timeline_events_time_idx ON timeline_events(timestamp)`,
  `CREATE INDEX IF NOT EXISTS timeline_events_kind_idx ON timeline_events(event_kind)`,
  `CREATE INDEX IF NOT EXISTS timeline_events_operation_idx ON timeline_events(operation_id)`,
  `CREATE INDEX IF NOT EXISTS timeline_events_change_idx ON timeline_events(change_id)`,
  `CREATE INDEX IF NOT EXISTS timeline_events_session_idx ON timeline_events(session_id)`,
  `CREATE INDEX IF NOT EXISTS timeline_entities_entity_idx ON timeline_entities(entity_kind, entity_name)`,
  `CREATE INDEX IF NOT EXISTS timeline_entities_event_idx ON timeline_entities(timeline_event_id)`,
  `CREATE INDEX IF NOT EXISTS timeline_edges_from_idx ON timeline_edges(from_event_id)`,
  `CREATE INDEX IF NOT EXISTS timeline_edges_to_idx ON timeline_edges(to_event_id)`,
  `CREATE INDEX IF NOT EXISTS agent_event_sources_name_idx ON agent_event_sources(source_name, integration_kind)`,
  `CREATE INDEX IF NOT EXISTS external_agent_events_source_idx ON external_agent_events(source_id, captured_at)`,
  `CREATE INDEX IF NOT EXISTS external_agent_events_kind_idx ON external_agent_events(event_kind)`,
  `CREATE INDEX IF NOT EXISTS agent_memory_events_kind_idx ON agent_memory_events(normalized_kind)`,
  `CREATE INDEX IF NOT EXISTS agent_memory_events_operation_idx ON agent_memory_events(operation_id)`,
];
