import type { IntegrationTemplateInput } from "./types.ts";

export function renderAiServerAdapter(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated Vercel AI SDK server adapter. */",
    'import { generateText, streamText, embed } from "ai";',
    "",
    "export { generateText, streamText, embed };",
    "",
    "export type ForgeAiServer = {",
    "  generateText: typeof generateText;",
    "  streamText: typeof streamText;",
    "  embed: typeof embed;",
    "};",
    "",
  ].join("\n");
}

export function renderAiGenerations(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated AI generation helpers. */",
    'import { generateText, type LanguageModel } from "ai";',
    "",
    "export async function runForgeGeneration(input: {",
    "  model: LanguageModel;",
    "  prompt: string;",
    "  system?: string;",
    "}) {",
    "  return generateText({",
    "    model: input.model,",
    "    prompt: input.prompt,",
    "    system: input.system,",
    "  });",
    "}",
    "",
  ].join("\n");
}

export function renderAiEvals(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated AI evaluation helpers. */",
    "",
    "export interface ForgeAiEvalCase {",
    "  name: string;",
    "  input: string;",
    "  expectedIncludes?: string;",
    "}",
    "",
    "export function scoreForgeEval(output: string, expectedIncludes?: string): boolean {",
    "  if (!expectedIncludes) return output.length > 0;",
    "  return output.includes(expectedIncludes);",
    "}",
    "",
  ].join("\n");
}

export function renderAiOpenaiProvider(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated OpenAI provider wiring. */",
    'import { createOpenAI } from "@ai-sdk/openai";',
    "",
    "export function createForgeOpenAiProvider(",
    "  apiKey = process.env.OPENAI_API_KEY,",
    ") {",
    '  if (!apiKey) throw new Error("OPENAI_API_KEY is required");',
    "  return createOpenAI({ apiKey });",
    "}",
    "",
    'export const forgeOpenAiSecret = "OPENAI_API_KEY" as const;',
    "",
  ].join("\n");
}

export function renderAiAnthropicProvider(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated Anthropic provider wiring. */",
    'import { createAnthropic } from "@ai-sdk/anthropic";',
    "",
    "export function createForgeAnthropicProvider(",
    "  apiKey = process.env.ANTHROPIC_API_KEY,",
    ") {",
    '  if (!apiKey) throw new Error("ANTHROPIC_API_KEY is required");',
    "  return createAnthropic({ apiKey });",
    "}",
    "",
    'export const forgeAnthropicSecret = "ANTHROPIC_API_KEY" as const;',
    "",
  ].join("\n");
}

export function renderAiTestkit(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated mock testkit for ai. */",
    "",
    "export function createAiMock() {",
    "  return {",
    '    generateText: async () => ({ text: "mock-generation", usage: { totalTokens: 1 } }),',
    '    streamText: async () => ({ textStream: (async function* () { yield "mock"; })() }),',
    '    embed: async () => ({ embedding: [0.1, 0.2, 0.3] }),',
    "  } as const;",
    "}",
    "",
  ].join("\n");
}

export function renderAiDoc(input: IntegrationTemplateInput): string {
  return [
    "# AI integration",
    "",
    "Generated by Forge (recipe v2).",
    "",
    "Nondeterministic/network package reference for server-side generation.",
    "",
    "## Integrations",
    "",
    "- `integrations/ai/generations.ts` — `generateText` wrapper",
    "- `integrations/ai/evals.ts` — lightweight eval scoring",
    "- `integrations/ai/providers/openai.ts` — OpenAI provider (`OPENAI_API_KEY`)",
    "- `integrations/ai/providers/anthropic.ts` — Anthropic provider (`ANTHROPIC_API_KEY`)",
    "",
    "## Validation",
    "",
    "- AI in `action` / `workflow` → passes",
    "- AI in `command` / `query` / `liveQuery` → `FORGE_GUARD_VIOLATION`",
    "",
    `Incompatible contexts: ${input.incompatible.join(", ")}`,
    "",
  ].join("\n");
}
