import type { IntegrationTemplateInput } from "./types.ts";

export function renderAiServerAdapter(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated AI server adapter — use ctx.ai at runtime, not raw SDK. */",
    'export type { AiContext, ForgeGenerateTextInput, ForgeGenerateTextResult } from "../aiContext.js";',
    "",
    "export const forgeAiRetainPrompts = false;",
    "export const forgeAiRetainOutputs = false;",
    "",
  ].join("\n");
}

export function renderAiGenerations(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated AI generation telemetry helpers. */",
    "",
    "export const FORGE_AI_GENERATION_EVENTS = [",
    '  "forge.ai.generation.started",',
    '  "forge.ai.generation.completed",',
    '  "forge.ai.generation.failed",',
    '  "forge.ai.stream.started",',
    '  "forge.ai.stream.completed",',
    '  "forge.ai.usage",',
    "] as const;",
    "",
    "export type ForgeAiGenerationEvent = (typeof FORGE_AI_GENERATION_EVENTS)[number];",
    "",
  ].join("\n");
}

export function renderAiTestkit(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated mock testkit for AI. */",
    "",
    "export interface MockAiQueuedResponse {",
    "  text: string;",
    "  usage?: { promptTokens?: number; completionTokens?: number; totalTokens?: number };",
    "}",
    "",
    "export function createMockAiProvider() {",
    "  const queue: MockAiQueuedResponse[] = [];",
    "  return {",
    "    enqueue(response: MockAiQueuedResponse) {",
    "      queue.push(response);",
    "    },",
    "    dequeue(): MockAiQueuedResponse {",
    "      return queue.shift() ?? { text: 'mock-ai-response', usage: { totalTokens: 30 } };",
    "    },",
    "    reset() {",
    "      queue.length = 0;",
    "    },",
    "  };",
    "}",
    "",
  ].join("\n");
}

export function renderAiTestkitLegacy(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated mock testkit for ai package alias. */",
    'export { createMockAiProvider } from "./testkit.js";',
    "",
  ].join("\n");
}

export function renderAiEvals(_input: IntegrationTemplateInput): string {
  return renderAiTestkit(_input);
}

export function renderAiOpenaiProvider(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated OpenAI provider wiring. */",
    'import { createOpenAI } from "@ai-sdk/openai";',
    'import type { SecretsContext } from "../secretsContext.js";',
    "",
    "export function createForgeOpenAiProvider(secrets: SecretsContext) {",
    '  const apiKey = secrets.get("OPENAI_API_KEY");',
    "  return createOpenAI({ apiKey });",
    "}",
    "",
    'export const forgeOpenAiSecret = "OPENAI_API_KEY" as const;',
    "",
  ].join("\n");
}

export function renderAiAnthropicProvider(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated Anthropic provider wiring. */",
    'import { createAnthropic } from "@ai-sdk/anthropic";',
    'import type { SecretsContext } from "../secretsContext.js";',
    "",
    "export function createForgeAnthropicProvider(secrets: SecretsContext) {",
    '  const apiKey = secrets.get("ANTHROPIC_API_KEY");',
    "  return createAnthropic({ apiKey });",
    "}",
    "",
    'export const forgeAnthropicSecret = "ANTHROPIC_API_KEY" as const;',
    "",
  ].join("\n");
}

export function renderAiDoc(input: IntegrationTemplateInput): string {
  return [
    "# AI integration",
    "",
    "Generated by Forge (H12).",
    "",
    "Use `ctx.ai` inside action, workflow, endpoint, and server contexts.",
    "Never import Vercel AI SDK directly from app code.",
    "",
    "## Runtime API",
    "",
    "- `ctx.ai.generateText({ provider, model, prompt, purpose })`",
    "- `ctx.ai.streamText({ provider, model, prompt })`",
    "- `ctx.ai.generateStructured({ provider, model, prompt, schema })`",
    "",
    "## Mock mode",
    "",
    "- `forge dev --mock-ai` or `FORGE_MOCK_AI=1`",
    "- `forge ai test --mock`",
    "",
    "## Validation",
    "",
    "- AI in `action` / `workflow` → passes",
    "- AI in `command` / `query` / `liveQuery` → `FORGE_AI_FORBIDDEN_CONTEXT`",
    "",
    `Incompatible contexts: ${input.incompatible.join(", ")}`,
    "",
  ].join("\n");
}
