import type { IntegrationTemplateInput } from "./types.ts";

export function renderPosthogClientAdapter(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated PostHog browser adapter. */",
    'import posthog from "posthog-js";',
    "",
    "export function createPosthogClient(",
    "  apiKey = process.env.NEXT_PUBLIC_POSTHOG_KEY,",
    '  options?: { api_host?: string; person_profiles?: "identified_only" | "always" },',
    ") {",
    '  if (!apiKey) throw new Error("NEXT_PUBLIC_POSTHOG_KEY is required for client adapter");',
    "  return posthog.init(apiKey, {",
    '    api_host: options?.api_host ?? process.env.NEXT_PUBLIC_POSTHOG_HOST ?? "https://us.i.posthog.com",',
    "    person_profiles: options?.person_profiles ?? \"identified_only\",",
    "    ...options,",
    "  });",
    "}",
    "",
    "export type ForgePosthogClient = typeof posthog;",
    "",
  ].join("\n");
}

export function renderPosthogServerAdapter(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated PostHog server adapter. */",
    'import { PostHog } from "posthog-node";',
    "",
    "export function createPosthogServer(",
    "  apiKey = process.env.POSTHOG_KEY,",
    "  host = process.env.POSTHOG_HOST,",
    "): PostHog {",
    '  if (!apiKey) throw new Error("POSTHOG_KEY is required for server adapter");',
    "  return new PostHog(apiKey, {",
    '    host: host ?? "https://us.i.posthog.com",',
    "  });",
    "}",
    "",
    "export type ForgePosthogServer = PostHog;",
    "",
  ].join("\n");
}

export function renderPosthogEvents(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated PostHog event capture helpers. */",
    'import type { PostHog } from "posthog-node";',
    'import type posthog from "posthog-js";',
    "",
    "export function captureServerEvent(",
    "  client: PostHog,",
    "  distinctId: string,",
    "  event: string,",
    "  properties?: Record<string, unknown>,",
    ") {",
    "  client.capture({ distinctId, event, properties });",
    "}",
    "",
    "export function captureClientEvent(",
    "  client: typeof posthog,",
    "  event: string,",
    "  properties?: Record<string, unknown>,",
    ") {",
    "  client.capture(event, properties);",
    "}",
    "",
  ].join("\n");
}

export function renderPosthogFlags(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated PostHog feature flag helpers. */",
    'import type { PostHog } from "posthog-node";',
    'import type posthog from "posthog-js";',
    "",
    "export async function isServerFeatureEnabled(",
    "  client: PostHog,",
    "  distinctId: string,",
    "  flag: string,",
    "): Promise<boolean> {",
    "  return client.isFeatureEnabled(flag, distinctId) ?? false;",
    "}",
    "",
    "export function isClientFeatureEnabled(",
    "  client: typeof posthog,",
    "  flag: string,",
    "): boolean {",
    "  return client.isFeatureEnabled(flag) ?? false;",
    "}",
    "",
  ].join("\n");
}

export function renderPosthogTestkit(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated mock testkit for posthog. */",
    "",
    "export function createPosthogMock() {",
    "  const flags = new Map<string, boolean>();",
    "  return {",
    "    capture: () => undefined,",
    "    identify: () => undefined,",
    "    isFeatureEnabled: (flag: string) => flags.get(flag) ?? false,",
    "    setFlag: (flag: string, value: boolean) => flags.set(flag, value),",
    "    shutdown: async () => undefined,",
    "  } as const;",
    "}",
    "",
  ].join("\n");
}

export function renderPosthogDoc(input: IntegrationTemplateInput): string {
  return [
    "# PostHog integration",
    "",
    "Generated by Forge (recipe v2).",
    "",
    "Client/server split reference.",
    "",
    "## Packages",
    "",
    "- `posthog-js` → client/shared contexts",
    "- `posthog-node` → server/action/workflow contexts",
    "",
    "## Integrations",
    "",
    "- `integrations/posthog/events.ts` — capture helpers",
    "- `integrations/posthog/flags.ts` — feature flag helpers",
    "",
    "## Validation",
    "",
    "- `posthog-js` in client → passes",
    "- `posthog-node` in action → passes",
    "- `posthog-node` in command → `FORGE_GUARD_VIOLATION`",
    "",
    `Packages: ${input.packageNames.join(", ")}`,
    "",
  ].join("\n");
}
