import type { IntegrationTemplateInput } from "./types.ts";

export function renderSentryClientAdapter(input: IntegrationTemplateInput): string {
  const framework = input.recipe.frameworkTarget ?? "nextjs";
  return [
    `/** Forge generated Sentry client adapter (${framework} target). */`,
    'import * as Sentry from "@sentry/nextjs";',
    "",
    "export function initSentryClient(options?: Sentry.BrowserOptions) {",
    "  Sentry.init({",
    "    dsn: process.env.SENTRY_DSN,",
    "    tracesSampleRate: 0.1,",
    "    ...options,",
    "  });",
    "}",
    "",
    "export { Sentry };",
    "",
  ].join("\n");
}

export function renderSentryServerAdapter(input: IntegrationTemplateInput): string {
  const framework = input.recipe.frameworkTarget ?? "nextjs";
  return [
    `/** Forge generated Sentry server adapter (${framework} target). */`,
    'import * as Sentry from "@sentry/nextjs";',
    "",
    "export function initSentryServer(options?: Sentry.NodeOptions) {",
    "  Sentry.init({",
    "    dsn: process.env.SENTRY_DSN,",
    "    tracesSampleRate: 0.1,",
    "    ...options,",
    "  });",
    "}",
    "",
    "export function captureServerException(error: unknown) {",
    "  return Sentry.captureException(error);",
    "}",
    "",
    "export { Sentry };",
    "",
  ].join("\n");
}

export function renderSentryErrors(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated Sentry error capture helpers. */",
    'import * as Sentry from "@sentry/nextjs";',
    "",
    "export function captureActionError(error: unknown, context?: Record<string, unknown>) {",
    "  if (context) {",
    "    Sentry.withScope((scope) => {",
    "      for (const [key, value] of Object.entries(context)) {",
    "        scope.setExtra(key, value);",
    "      }",
    "      Sentry.captureException(error);",
    "    });",
    "    return;",
    "  }",
    "  Sentry.captureException(error);",
    "}",
    "",
  ].join("\n");
}

export function renderSentryReleases(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated Sentry release tracking helpers. */",
    "",
    "export function resolveSentryRelease(",
    "  release = process.env.SENTRY_RELEASE,",
    "  commit = process.env.VERCEL_GIT_COMMIT_SHA,",
    "): string | undefined {",
    "  return release ?? commit;",
    "}",
    "",
    "export const sentryReleaseEnvVars = [",
    '  "SENTRY_RELEASE",',
    '  "VERCEL_GIT_COMMIT_SHA",',
    "] as const;",
    "",
  ].join("\n");
}

export function renderSentrySourcemaps(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated Sentry source map upload configuration (names only). */",
    "",
    "export const sentrySourceMapEnvVars = {",
    '  authToken: "SENTRY_AUTH_TOKEN",',
    '  org: "SENTRY_ORG",',
    '  project: "SENTRY_PROJECT",',
    "} as const;",
    "",
    "export function describeSentrySourceMapUpload(): string {",
    '  return "Configure SENTRY_AUTH_TOKEN, SENTRY_ORG, and SENTRY_PROJECT for CI source map uploads.";',
    "}",
    "",
  ].join("\n");
}

export function renderSentryTestkit(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated mock testkit for sentry. */",
    "",
    "export function createSentryMock() {",
    "  const events: unknown[] = [];",
    "  return {",
    "    captureException: (error: unknown) => {",
    "      events.push(error);",
    "      return \"mock-event-id\";",
    "    },",
    "    getEvents: () => [...events],",
    "    init: () => undefined,",
    "  } as const;",
    "}",
    "",
  ].join("\n");
}

export function renderSentryDoc(input: IntegrationTemplateInput): string {
  const framework = input.recipe.frameworkTarget ?? "nextjs";
  return [
    "# Sentry integration",
    "",
    "Generated by Forge (recipe v2).",
    "",
    `Framework target: **${framework}** (uses \`@sentry/nextjs\`).`,
    "",
    "## Integrations",
    "",
    "- `integrations/sentry/errors.ts` — server/action error capture",
    "- `integrations/sentry/releases.ts` — release tracking",
    "- `integrations/sentry/sourcemaps.ts` — source map env vars for CI",
    "",
    "## Source map env vars",
    "",
    "- `SENTRY_AUTH_TOKEN`",
    "- `SENTRY_ORG`",
    "- `SENTRY_PROJECT`",
    "",
    "## Validation",
    "",
    "- Sentry server capture in `action` → passes",
    "- Direct Sentry capture in `command` → `FORGE_GUARD_VIOLATION`",
    "",
  ].join("\n");
}
