import type { IntegrationTemplateInput } from "./types.ts";

const SECRETS_IMPORT = 'import type { SecretsContext } from "../secretsContext.js";';

export function renderStripeServerAdapter(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated Stripe server adapter — action/workflow/endpoint contexts. */",
    'import Stripe from "stripe";',
    SECRETS_IMPORT,
    "",
    'const DEFAULT_API_VERSION = "2024-11-20.acacia" as Stripe.LatestApiVersion;',
    "",
    "export function createStripeClient(secrets: SecretsContext): Stripe {",
    '  const secretKey = secrets.get("STRIPE_SECRET_KEY");',
    "  return new Stripe(secretKey, { apiVersion: DEFAULT_API_VERSION });",
    "}",
    "",
    "export type ForgeStripeServerClient = Stripe;",
    "",
  ].join("\n");
}

export function renderStripeWorkflowAdapter(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated Stripe workflow adapter — durable workflow steps only. */",
    'import type Stripe from "stripe";',
    'import { createStripeClient } from "./stripe.server.js";',
    SECRETS_IMPORT,
    "",
    "export function createStripeWorkflowClient(secrets: SecretsContext): Stripe {",
    "  return createStripeClient(secrets);",
    "}",
    "",
  ].join("\n");
}

export function renderStripeWebhook(input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated Stripe webhook verification helper. */",
    'import Stripe from "stripe";',
    SECRETS_IMPORT,
    "",
    "export function constructStripeWebhookEvent(",
    "  payload: string | Buffer,",
    "  signature: string,",
    "  secrets: SecretsContext,",
    "): Stripe.Event {",
    '  const secret = secrets.get("STRIPE_WEBHOOK_SECRET");',
    "  return Stripe.webhooks.constructEvent(payload, signature, secret);",
    "}",
    "",
    `// Secrets (names only): ${input.secrets.map((s) => s.envVar).join(", ")}`,
    "",
  ].join("\n");
}

export function renderStripeTestkit(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated mock testkit for stripe. */",
    "",
    "export function createStripeMock() {",
    "  return {",
    "    customers: {",
    "      create: async () => ({ id: \"cus_forge_mock\" }),",
    "      retrieve: async (id: string) => ({ id, email: \"test@forge.local\" }),",
    "    },",
    "    checkout: {",
    "      sessions: {",
    "        create: async () => ({ id: \"cs_forge_mock\", url: \"https://checkout.forge.test\" }),",
    "      },",
    "    },",
    "    webhooks: {",
    "      constructEvent: () => ({ type: \"checkout.session.completed\", data: { object: {} } }),",
    "    },",
    "  } as const;",
    "}",
    "",
  ].join("\n");
}

export function renderStripeDoc(input: IntegrationTemplateInput): string {
  return [
    "# Stripe integration",
    "",
    "Generated by Forge (recipe v2).",
    "",
    "Server/action/workflow package reference. **Not allowed in command/query/liveQuery.**",
    "",
    "## Adapters",
    "",
    "- `packages/stripe.server.ts` — server/action client factory (`ctx.secrets`)",
    "- `packages/stripe.workflow.ts` — workflow-safe client",
    "- `integrations/stripe/webhook.ts` — webhook signature verification",
    "",
    "## Secrets (names only)",
    "",
    input.secrets.map((s) => `- \`${s.envVar}\``).join("\n"),
    "",
    "## Validation",
    "",
    "- Stripe in `action` → passes",
    "- Stripe in `command` → `FORGE_GUARD_VIOLATION`",
    "- Transitive stripe in command → fails",
    '- `import type Stripe from "stripe"` in command → passes (type-only)',
    "",
    `Incompatible contexts: ${input.incompatible.join(", ")}`,
    "",
  ].join("\n");
}
