import type { IntegrationTemplateInput } from "./types.ts";

export function renderZodAdapter(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated — pure validation reference (all runtime contexts). */",
    'import { z } from "zod";',
    "",
    "export { z };",
    'export type { ZodSchema, ZodType, ZodTypeDef } from "zod";',
    "",
    "/** Safe in command, client, server, and every Forge context. */",
    "export const forgeZod = z;",
    "",
  ].join("\n");
}

export function renderZodTestkit(_input: IntegrationTemplateInput): string {
  return [
    "/** Forge generated mock testkit for zod. */",
    'import { z } from "zod";',
    "",
    "export function createZodMock() {",
    "  return {",
    "    parse: <T>(schema: z.ZodType<T>, value: unknown) => schema.parse(value),",
    "    safeParse: <T>(schema: z.ZodType<T>, value: unknown) => schema.safeParse(value),",
    "  } as const;",
    "}",
    "",
  ].join("\n");
}

export function renderZodDoc(input: IntegrationTemplateInput): string {
  return [
    "# Zod integration",
    "",
    "Generated by Forge (recipe v2).",
    "",
    "Zod is a **pure package reference** — allowed in every runtime context.",
    "",
    "## Usage",
    "",
    "```ts",
    'import { z, forgeZod } from "./packages/zod.shared";',
    "",
    "const schema = forgeZod.object({ id: z.string() });",
    "```",
    "",
    "## Validation",
    "",
    "- Import in `command` → passes",
    "- Import in `client` → passes",
    `- Compatible contexts: ${input.compatible.join(", ")}`,
    "",
  ].join("\n");
}
