import type { SecretRequirement } from "../types/capability.ts";
import type { RuntimeContext } from "../types/runtime.ts";
import { RUNTIME_CONTEXTS } from "../types/runtime.ts";
import { serializeCanonical } from "../primitives/serialize.ts";

function capitalizeSegment(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

export function parseAdapterContext(filename: string): RuntimeContext | null {
  const base = filename.replace(/\.ts$/, "");
  for (const context of RUNTIME_CONTEXTS) {
    if (base.endsWith(`.${context}`)) {
      return context;
    }
  }
  return null;
}

export function renderAdapterModule(input: {
  alias: string;
  context: RuntimeContext;
  packageName: string;
  secrets: SecretRequirement[];
}): string {
  const secretNames = input.secrets.map((secret) => secret.envVar).sort();
  const exportName = `forge${capitalizeSegment(input.alias)}${capitalizeSegment(input.context)}Adapter`;

  return [
    `/** Forge generated adapter for ${input.alias} (${input.context} context). */`,
    `export const ${exportName} = ${serializeCanonical({
      alias: input.alias,
      packageName: input.packageName,
      context: input.context,
      secrets: secretNames,
    }).trim()} as const;`,
    "",
  ].join("\n");
}

export function renderTestkitModule(alias: string, packageName: string): string {
  const exportName = `create${capitalizeSegment(alias)}Mock`;
  return [
    `/** Forge generated mock testkit for ${alias}. */`,
    `export function ${exportName}() {`,
    `  return ${serializeCanonical({
      alias,
      packageName,
      mocked: true,
    }).trim()} as const;`,
    `}`,
    "",
  ].join("\n");
}

export function renderIntegrationDoc(input: {
  alias: string;
  packageNames: string[];
  secrets: SecretRequirement[];
  compatible: RuntimeContext[];
  incompatible: RuntimeContext[];
}): string {
  const secretNames = input.secrets.map((secret) => secret.envVar).sort();
  const lines = [
    `# ${input.alias} integration`,
    "",
    "Generated by Forge.",
    "",
    `Packages: ${input.packageNames.join(", ")}`,
    "",
    `Compatible contexts: ${input.compatible.join(", ")}`,
    "",
    `Incompatible contexts: ${input.incompatible.join(", ")}`,
    "",
  ];

  if (secretNames.length > 0) {
    lines.push(`Secrets (names only): ${secretNames.join(", ")}`, "");
  }

  return lines.join("\n");
}
