import type { SecretRequirement } from "../types/capability.ts";
import type { AppGraph } from "../types/app-graph.ts";
import type { IntegrationRecipe } from "../types/integration.ts";
import type { RuntimeContext } from "../types/runtime.ts";
import { RUNTIME_CONTEXTS } from "../types/runtime.ts";
import { serializeCanonical } from "../primitives/serialize.ts";
import {
  buildTemplateInput,
  renderQualityAdapter,
  renderQualityDoc,
  renderQualityIntegration,
  renderQualityRootFile,
  renderQualityTestkit,
} from "./templates/index.ts";
import type { IntegrationTemplateInput } from "./templates/types.ts";

function capitalizeSegment(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

export function parseAdapterContext(filename: string): RuntimeContext | null {
  const base = filename.replace(/\.ts$/, "");
  for (const context of RUNTIME_CONTEXTS) {
    if (base.endsWith(`.${context}`)) {
      return context;
    }
  }
  return null;
}

function skeletonAdapter(input: IntegrationTemplateInput): string {
  const secretNames = input.secrets.map((secret) => secret.envVar).sort();
  const exportName = `forge${capitalizeSegment(input.alias)}${capitalizeSegment(input.context)}Adapter`;

  return [
    `/** Forge generated adapter for ${input.alias} (${input.context} context). */`,
    `export const ${exportName} = ${serializeCanonical({
      alias: input.alias,
      packageName: input.packageName,
      context: input.context,
      secrets: secretNames,
    }).trim()} as const;`,
    "",
  ].join("\n");
}

function skeletonTestkit(alias: string, packageName: string): string {
  const exportName = `create${capitalizeSegment(alias)}Mock`;
  return [
    `/** Forge generated mock testkit for ${alias}. */`,
    `export function ${exportName}() {`,
    `  return ${serializeCanonical({
      alias,
      packageName,
      mocked: true,
    }).trim()} as const;`,
    `}`,
    "",
  ].join("\n");
}

function skeletonDoc(input: IntegrationTemplateInput): string {
  const secretNames = input.secrets.map((secret) => secret.envVar).sort();
  const lines = [
    `# ${input.alias} integration`,
    "",
    "Generated by Forge.",
    "",
    `Packages: ${input.packageNames.join(", ")}`,
    "",
    `Compatible contexts: ${input.compatible.join(", ")}`,
    "",
    `Incompatible contexts: ${input.incompatible.join(", ")}`,
    "",
  ];

  if (secretNames.length > 0) {
    lines.push(`Secrets (names only): ${secretNames.join(", ")}`, "");
  }

  return lines.join("\n");
}

export function createRenderContext(input: {
  alias: string;
  recipe: IntegrationRecipe;
  context: RuntimeContext;
  packageName: string;
  packageNames: string[];
  secrets: SecretRequirement[];
  compatible: RuntimeContext[];
  incompatible: RuntimeContext[];
  workspaceRoot?: string;
  appGraph?: AppGraph;
}): IntegrationTemplateInput {
  return buildTemplateInput(input);
}

export function renderAdapterModule(input: {
  alias: string;
  recipe: IntegrationRecipe;
  context: RuntimeContext;
  packageName: string;
  packageNames: string[];
  secrets: SecretRequirement[];
  compatible: RuntimeContext[];
  incompatible: RuntimeContext[];
  workspaceRoot?: string;
  appGraph?: AppGraph;
}): string {
  const ctx = createRenderContext(input);
  const adapterFilename = `${input.alias}.${input.context}.ts`;
  const quality = renderQualityAdapter(adapterFilename, ctx);
  if (quality) {
    return quality;
  }

  const resolvedName = input.recipe.adapters.find((name) =>
    parseAdapterContext(name) === input.context,
  );
  if (resolvedName) {
    const byName = renderQualityAdapter(resolvedName, ctx);
    if (byName) {
      return byName;
    }
  }

  return skeletonAdapter(ctx);
}

export function renderIntegrationModule(
  relativePath: string,
  input: IntegrationTemplateInput,
): string {
  const quality = renderQualityIntegration(relativePath, input);
  if (quality) {
    return quality;
  }

  return [
    `/** Forge generated integration module: ${relativePath} */`,
    `export const forgeIntegration = ${serializeCanonical({
      alias: input.alias,
      module: relativePath,
    }).trim()} as const;`,
    "",
  ].join("\n");
}

export function renderTestkitModule(
  alias: string,
  packageName: string,
  input?: IntegrationTemplateInput,
): string {
  const filename = `${alias}.mock.ts`;
  if (input) {
    const quality = renderQualityTestkit(filename, input);
    if (quality) {
      return quality;
    }
  }
  return skeletonTestkit(alias, packageName);
}

export function renderIntegrationDoc(input: {
  alias: string;
  recipe: IntegrationRecipe;
  packageNames: string[];
  secrets: SecretRequirement[];
  compatible: RuntimeContext[];
  incompatible: RuntimeContext[];
  workspaceRoot?: string;
  appGraph?: AppGraph;
}): string {
  const ctx = buildTemplateInput({
    alias: input.alias,
    recipe: input.recipe,
    context: "shared",
    packageName: input.packageNames[0] ?? input.alias,
    packageNames: input.packageNames,
    secrets: input.secrets,
    compatible: input.compatible,
    incompatible: input.incompatible,
    workspaceRoot: input.workspaceRoot,
    appGraph: input.appGraph,
  });

  const docName = `${input.alias}.md`;
  const quality = renderQualityDoc(docName, ctx);
  if (quality) {
    return quality;
  }

  return skeletonDoc(ctx);
}

export function renderRootFile(
  relativePath: string,
  input: IntegrationTemplateInput,
): string {
  const quality = renderQualityRootFile(relativePath, input);
  if (quality) {
    return quality;
  }

  return [
    `/** Forge generated root file for ${input.alias}: ${relativePath}. */`,
    `export const forgeIntegrationRootFile = ${serializeCanonical({
      alias: input.alias,
      path: relativePath,
    }).trim()} as const;`,
    "",
  ].join("\n");
}
