/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in installed apps. It is included here so
// template type checks have a stable entrypoint before first `next dev`.
