export const FORGE_DUP_SYMBOL = "FORGE_DUP_SYMBOL" as const;
export const FORGE_DRIFT = "FORGE_DRIFT" as const;
export const FORGE_PKG_NO_TYPES = "FORGE_PKG_NO_TYPES" as const;
export const FORGE_GUARD_VIOLATION = "FORGE_GUARD_VIOLATION" as const;
export const FORGE_SANDBOX_LIMIT = "FORGE_SANDBOX_LIMIT" as const;
export const FORGE_SECRET_LEAK = "FORGE_SECRET_LEAK" as const;
export const FORGE_ORPHANED_GENERATED_FILE =
  "FORGE_ORPHANED_GENERATED_FILE" as const;
export const FORGE_SANDBOX_ABNORMAL = "FORGE_SANDBOX_ABNORMAL" as const;
export const FORGE_DUP_RUNTIME_ENTRY = "FORGE_DUP_RUNTIME_ENTRY" as const;
export const FORGE_RUNTIME_UNRESOLVABLE = "FORGE_RUNTIME_UNRESOLVABLE" as const;
export const FORGE_RUNTIME_NOT_FOUND = "FORGE_RUNTIME_NOT_FOUND" as const;
export const FORGE_RUNTIME_GUARD_BLOCKED = "FORGE_RUNTIME_GUARD_BLOCKED" as const;
export const FORGE_DEV_SERVER_ERROR = "FORGE_DEV_SERVER_ERROR" as const;
export const FORGE_DEV_WATCH_FAILED = "FORGE_DEV_WATCH_FAILED" as const;
export const FORGE_DEV_INVOKE_FAILED = "FORGE_DEV_INVOKE_FAILED" as const;
export const FORGE_DB_CONNECT_FAILED = "FORGE_DB_CONNECT_FAILED" as const;
export const FORGE_DB_MIGRATION_FAILED = "FORGE_DB_MIGRATION_FAILED" as const;
export const FORGE_DB_UNSUPPORTED_FIELD_TYPE =
  "FORGE_DB_UNSUPPORTED_FIELD_TYPE" as const;
export const FORGE_DB_INVALID_SQL_PLAN = "FORGE_DB_INVALID_SQL_PLAN" as const;
export const FORGE_DB_TRANSACTION_FAILED = "FORGE_DB_TRANSACTION_FAILED" as const;
export const FORGE_DB_OUTBOX_WRITE_FAILED = "FORGE_DB_OUTBOX_WRITE_FAILED" as const;
export const FORGE_DB_ADAPTER_UNAVAILABLE = "FORGE_DB_ADAPTER_UNAVAILABLE" as const;
export const FORGE_OUTBOX_PROCESS_FAILED = "FORGE_OUTBOX_PROCESS_FAILED" as const;
export const FORGE_OUTBOX_NO_SUBSCRIPTIONS = "FORGE_OUTBOX_NO_SUBSCRIPTIONS" as const;
export const FORGE_OUTBOX_DELIVERY_NOT_FOUND = "FORGE_OUTBOX_DELIVERY_NOT_FOUND" as const;
export const FORGE_ACTION_EVENT_UNPARSEABLE = "FORGE_ACTION_EVENT_UNPARSEABLE" as const;
export const FORGE_WORKFLOW_UNKNOWN = "FORGE_WORKFLOW_UNKNOWN" as const;
export const FORGE_WORKFLOW_STEP_FAILED = "FORGE_WORKFLOW_STEP_FAILED" as const;
export const FORGE_WORKFLOW_STEP_DEAD = "FORGE_WORKFLOW_STEP_DEAD" as const;
export const FORGE_WORKFLOW_RUN_NOT_FOUND = "FORGE_WORKFLOW_RUN_NOT_FOUND" as const;
export const FORGE_WORKFLOW_DUPLICATE_RUN = "FORGE_WORKFLOW_DUPLICATE_RUN" as const;
export const FORGE_WORKFLOW_INVALID_TRIGGER = "FORGE_WORKFLOW_INVALID_TRIGGER" as const;
export const FORGE_WORKFLOW_INVALID_STEP = "FORGE_WORKFLOW_INVALID_STEP" as const;
export const FORGE_WORKFLOW_CANCELED = "FORGE_WORKFLOW_CANCELED" as const;
export const FORGE_TELEMETRY_SECRET_REDACTED =
  "FORGE_TELEMETRY_SECRET_REDACTED" as const;
export const FORGE_TELEMETRY_PAYLOAD_TRUNCATED =
  "FORGE_TELEMETRY_PAYLOAD_TRUNCATED" as const;
export const FORGE_TELEMETRY_SINK_FAILED = "FORGE_TELEMETRY_SINK_FAILED" as const;
export const FORGE_TELEMETRY_UNKNOWN_SINK = "FORGE_TELEMETRY_UNKNOWN_SINK" as const;
export const FORGE_POLICY_DENIED = "FORGE_POLICY_DENIED" as const;
export const FORGE_POLICY_MISSING = "FORGE_POLICY_MISSING" as const;
export const FORGE_POLICY_UNKNOWN = "FORGE_POLICY_UNKNOWN" as const;
export const FORGE_POLICY_DUPLICATE = "FORGE_POLICY_DUPLICATE" as const;
export const FORGE_POLICY_ROLE_EMPTY = "FORGE_POLICY_ROLE_EMPTY" as const;
export const FORGE_TENANT_TABLE_WITHOUT_TENANT_ID =
  "FORGE_TENANT_TABLE_WITHOUT_TENANT_ID" as const;
export const FORGE_TENANT_SCOPE_VIOLATION = "FORGE_TENANT_SCOPE_VIOLATION" as const;
export const FORGE_SECRET_MISSING = "FORGE_SECRET_MISSING" as const;
export const FORGE_SECRET_FORBIDDEN_CONTEXT =
  "FORGE_SECRET_FORBIDDEN_CONTEXT" as const;
export const FORGE_SECRET_DIRECT_PROCESS_ENV =
  "FORGE_SECRET_DIRECT_PROCESS_ENV" as const;
export const FORGE_ENV_PUBLIC_SECRET = "FORGE_ENV_PUBLIC_SECRET" as const;
export const FORGE_ENV_UNKNOWN_REQUIRED = "FORGE_ENV_UNKNOWN_REQUIRED" as const;
export const FORGE_VERIFY_POLICY = "FORGE_VERIFY_POLICY" as const;
export const FORGE_AI_FORBIDDEN_CONTEXT = "FORGE_AI_FORBIDDEN_CONTEXT" as const;
export const FORGE_AI_PROVIDER_UNKNOWN = "FORGE_AI_PROVIDER_UNKNOWN" as const;
export const FORGE_AI_MODEL_MISSING = "FORGE_AI_MODEL_MISSING" as const;
export const FORGE_AI_SECRET_MISSING = "FORGE_AI_SECRET_MISSING" as const;
export const FORGE_AI_DYNAMIC_PROVIDER = "FORGE_AI_DYNAMIC_PROVIDER" as const;
export const FORGE_AI_GENERATION_FAILED = "FORGE_AI_GENERATION_FAILED" as const;
export const FORGE_AI_USAGE_UNAVAILABLE = "FORGE_AI_USAGE_UNAVAILABLE" as const;
export const FORGE_QUERY_WRITE_FORBIDDEN = "FORGE_QUERY_WRITE_FORBIDDEN" as const;
export const FORGE_QUERY_EMIT_FORBIDDEN = "FORGE_QUERY_EMIT_FORBIDDEN" as const;
export const FORGE_QUERY_SECRET_FORBIDDEN = "FORGE_QUERY_SECRET_FORBIDDEN" as const;
export const FORGE_QUERY_AI_FORBIDDEN = "FORGE_QUERY_AI_FORBIDDEN" as const;
export const FORGE_QUERY_INTEGRATION_FORBIDDEN =
  "FORGE_QUERY_INTEGRATION_FORBIDDEN" as const;
export const FORGE_QUERY_NOT_FOUND = "FORGE_QUERY_NOT_FOUND" as const;
export const FORGE_QUERY_FAILED = "FORGE_QUERY_FAILED" as const;
export const FORGE_LIVEQUERY_WRITE_FORBIDDEN =
  "FORGE_LIVEQUERY_WRITE_FORBIDDEN" as const;
export const FORGE_LIVEQUERY_EMIT_FORBIDDEN =
  "FORGE_LIVEQUERY_EMIT_FORBIDDEN" as const;
export const FORGE_LIVEQUERY_SECRET_FORBIDDEN =
  "FORGE_LIVEQUERY_SECRET_FORBIDDEN" as const;
export const FORGE_LIVEQUERY_AI_FORBIDDEN =
  "FORGE_LIVEQUERY_AI_FORBIDDEN" as const;
export const FORGE_LIVEQUERY_INTEGRATION_FORBIDDEN =
  "FORGE_LIVEQUERY_INTEGRATION_FORBIDDEN" as const;
export const FORGE_LIVEQUERY_POLICY_DENIED =
  "FORGE_LIVEQUERY_POLICY_DENIED" as const;
export const FORGE_LIVEQUERY_UNKNOWN = "FORGE_LIVEQUERY_UNKNOWN" as const;
export const FORGE_LIVEQUERY_SUBSCRIPTION_FAILED =
  "FORGE_LIVEQUERY_SUBSCRIPTION_FAILED" as const;
export const FORGE_LIVEQUERY_RERUN_FAILED =
  "FORGE_LIVEQUERY_RERUN_FAILED" as const;

export const DIAGNOSTIC_CODES = [
  FORGE_DUP_SYMBOL,
  FORGE_DRIFT,
  FORGE_PKG_NO_TYPES,
  FORGE_GUARD_VIOLATION,
  FORGE_SANDBOX_LIMIT,
  FORGE_SECRET_LEAK,
  FORGE_ORPHANED_GENERATED_FILE,
  FORGE_SANDBOX_ABNORMAL,
  FORGE_DUP_RUNTIME_ENTRY,
  FORGE_RUNTIME_UNRESOLVABLE,
  FORGE_RUNTIME_NOT_FOUND,
  FORGE_RUNTIME_GUARD_BLOCKED,
  FORGE_DEV_SERVER_ERROR,
  FORGE_DEV_WATCH_FAILED,
  FORGE_DEV_INVOKE_FAILED,
  FORGE_DB_CONNECT_FAILED,
  FORGE_DB_MIGRATION_FAILED,
  FORGE_DB_UNSUPPORTED_FIELD_TYPE,
  FORGE_DB_INVALID_SQL_PLAN,
  FORGE_DB_TRANSACTION_FAILED,
  FORGE_DB_OUTBOX_WRITE_FAILED,
  FORGE_DB_ADAPTER_UNAVAILABLE,
  FORGE_OUTBOX_PROCESS_FAILED,
  FORGE_OUTBOX_NO_SUBSCRIPTIONS,
  FORGE_OUTBOX_DELIVERY_NOT_FOUND,
  FORGE_ACTION_EVENT_UNPARSEABLE,
  FORGE_WORKFLOW_UNKNOWN,
  FORGE_WORKFLOW_STEP_FAILED,
  FORGE_WORKFLOW_STEP_DEAD,
  FORGE_WORKFLOW_RUN_NOT_FOUND,
  FORGE_WORKFLOW_DUPLICATE_RUN,
  FORGE_WORKFLOW_INVALID_TRIGGER,
  FORGE_WORKFLOW_INVALID_STEP,
  FORGE_WORKFLOW_CANCELED,
  FORGE_TELEMETRY_SECRET_REDACTED,
  FORGE_TELEMETRY_PAYLOAD_TRUNCATED,
  FORGE_TELEMETRY_SINK_FAILED,
  FORGE_TELEMETRY_UNKNOWN_SINK,
  FORGE_POLICY_DENIED,
  FORGE_POLICY_MISSING,
  FORGE_POLICY_UNKNOWN,
  FORGE_POLICY_DUPLICATE,
  FORGE_POLICY_ROLE_EMPTY,
  FORGE_TENANT_TABLE_WITHOUT_TENANT_ID,
  FORGE_TENANT_SCOPE_VIOLATION,
  FORGE_SECRET_MISSING,
  FORGE_SECRET_FORBIDDEN_CONTEXT,
  FORGE_SECRET_DIRECT_PROCESS_ENV,
  FORGE_ENV_PUBLIC_SECRET,
  FORGE_ENV_UNKNOWN_REQUIRED,
  FORGE_VERIFY_POLICY,
  FORGE_AI_FORBIDDEN_CONTEXT,
  FORGE_AI_PROVIDER_UNKNOWN,
  FORGE_AI_MODEL_MISSING,
  FORGE_AI_SECRET_MISSING,
  FORGE_AI_DYNAMIC_PROVIDER,
  FORGE_AI_GENERATION_FAILED,
  FORGE_AI_USAGE_UNAVAILABLE,
  FORGE_QUERY_WRITE_FORBIDDEN,
  FORGE_QUERY_EMIT_FORBIDDEN,
  FORGE_QUERY_SECRET_FORBIDDEN,
  FORGE_QUERY_AI_FORBIDDEN,
  FORGE_QUERY_INTEGRATION_FORBIDDEN,
  FORGE_QUERY_NOT_FOUND,
  FORGE_QUERY_FAILED,
  FORGE_LIVEQUERY_WRITE_FORBIDDEN,
  FORGE_LIVEQUERY_EMIT_FORBIDDEN,
  FORGE_LIVEQUERY_SECRET_FORBIDDEN,
  FORGE_LIVEQUERY_AI_FORBIDDEN,
  FORGE_LIVEQUERY_INTEGRATION_FORBIDDEN,
  FORGE_LIVEQUERY_POLICY_DENIED,
  FORGE_LIVEQUERY_UNKNOWN,
  FORGE_LIVEQUERY_SUBSCRIPTION_FAILED,
  FORGE_LIVEQUERY_RERUN_FAILED,
] as const;

export type DiagnosticCode = (typeof DIAGNOSTIC_CODES)[number];
