export const FORGE_DUP_SYMBOL = "FORGE_DUP_SYMBOL" as const;
export const FORGE_DRIFT = "FORGE_DRIFT" as const;
export const FORGE_GENERATE_LOCKED = "FORGE_GENERATE_LOCKED" as const;
export const FORGE_PKG_NO_TYPES = "FORGE_PKG_NO_TYPES" as const;
export const FORGE_GUARD_VIOLATION = "FORGE_GUARD_VIOLATION" as const;
export const FORGE_SANDBOX_LIMIT = "FORGE_SANDBOX_LIMIT" as const;
export const FORGE_SECRET_LEAK = "FORGE_SECRET_LEAK" as const;
export const FORGE_AGENT_CONTRACT_SECRET_LEAK =
  "FORGE_AGENT_CONTRACT_SECRET_LEAK" as const;
export const FORGE_AUTH_MISSING_TOKEN = "FORGE_AUTH_MISSING_TOKEN" as const;
export const FORGE_AUTH_INVALID_TOKEN = "FORGE_AUTH_INVALID_TOKEN" as const;
export const FORGE_AUTH_INVALID_ISSUER = "FORGE_AUTH_INVALID_ISSUER" as const;
export const FORGE_AUTH_INVALID_AUDIENCE = "FORGE_AUTH_INVALID_AUDIENCE" as const;
export const FORGE_AUTH_TOKEN_EXPIRED = "FORGE_AUTH_TOKEN_EXPIRED" as const;
export const FORGE_AUTH_JWKS_FAILED = "FORGE_AUTH_JWKS_FAILED" as const;
export const FORGE_AUTH_CLAIM_MISSING = "FORGE_AUTH_CLAIM_MISSING" as const;
export const FORGE_AUTH_CLAIM_INVALID = "FORGE_AUTH_CLAIM_INVALID" as const;
export const FORGE_AUTH_TENANT_MISSING = "FORGE_AUTH_TENANT_MISSING" as const;
export const FORGE_AUTH_DEV_HEADERS_IN_PRODUCTION =
  "FORGE_AUTH_DEV_HEADERS_IN_PRODUCTION" as const;
export const FORGE_AUTH_MODE_INVALID = "FORGE_AUTH_MODE_INVALID" as const;
export const FORGE_AUTH_DISABLED = "FORGE_AUTH_DISABLED" as const;
export const FORGE_ORPHANED_GENERATED_FILE =
  "FORGE_ORPHANED_GENERATED_FILE" as const;
export const FORGE_SANDBOX_ABNORMAL = "FORGE_SANDBOX_ABNORMAL" as const;
export const FORGE_DUP_RUNTIME_ENTRY = "FORGE_DUP_RUNTIME_ENTRY" as const;
export const FORGE_RUNTIME_UNRESOLVABLE = "FORGE_RUNTIME_UNRESOLVABLE" as const;
export const FORGE_RUNTIME_NOT_FOUND = "FORGE_RUNTIME_NOT_FOUND" as const;
export const FORGE_RUNTIME_GUARD_BLOCKED = "FORGE_RUNTIME_GUARD_BLOCKED" as const;
export const FORGE_RUNTIME_EXPORT_NAME_REQUIRED =
  "FORGE_RUNTIME_EXPORT_NAME_REQUIRED" as const;
export const FORGE_EXTERNAL_RUNTIME_NOT_FOUND =
  "FORGE_EXTERNAL_RUNTIME_NOT_FOUND" as const;
export const FORGE_EXTERNAL_RUNTIME_UNSUPPORTED =
  "FORGE_EXTERNAL_RUNTIME_UNSUPPORTED" as const;
export const FORGE_EXTERNAL_RUNTIME_FAILED =
  "FORGE_EXTERNAL_RUNTIME_FAILED" as const;
export const FORGE_EXTERNAL_RUNTIME_BAD_RESPONSE =
  "FORGE_EXTERNAL_RUNTIME_BAD_RESPONSE" as const;
export const FORGE_DEV_SERVER_ERROR = "FORGE_DEV_SERVER_ERROR" as const;
export const FORGE_DEV_WATCH_FAILED = "FORGE_DEV_WATCH_FAILED" as const;
export const FORGE_DEV_INVOKE_FAILED = "FORGE_DEV_INVOKE_FAILED" as const;
export const FORGE_DEV_DOCTOR_MISSING_ARTIFACT =
  "FORGE_DEV_DOCTOR_MISSING_ARTIFACT" as const;
export const FORGE_DEV_DB_RESET = "FORGE_DEV_DB_RESET" as const;
export const FORGE_DB_CONNECT_FAILED = "FORGE_DB_CONNECT_FAILED" as const;
export const FORGE_DB_MIGRATION_FAILED = "FORGE_DB_MIGRATION_FAILED" as const;
export const FORGE_DB_UNSUPPORTED_FIELD_TYPE =
  "FORGE_DB_UNSUPPORTED_FIELD_TYPE" as const;
export const FORGE_DB_INVALID_SQL_PLAN = "FORGE_DB_INVALID_SQL_PLAN" as const;
export const FORGE_DB_INVALID_ID_FIELD =
  "FORGE_DB_INVALID_ID_FIELD" as const;
export const FORGE_DB_EMPTY_TIMESTAMP_LITERAL =
  "FORGE_DB_EMPTY_TIMESTAMP_LITERAL" as const;
export const FORGE_DB_TRANSACTION_FAILED = "FORGE_DB_TRANSACTION_FAILED" as const;
export const FORGE_DB_OUTBOX_WRITE_FAILED = "FORGE_DB_OUTBOX_WRITE_FAILED" as const;
export const FORGE_DB_ADAPTER_UNAVAILABLE = "FORGE_DB_ADAPTER_UNAVAILABLE" as const;
export const FORGE_PGLITE_STORE_ABORTED = "FORGE_PGLITE_STORE_ABORTED" as const;
export const FORGE_PGLITE_STORE_ACTIVE = "FORGE_PGLITE_STORE_ACTIVE" as const;
export const FORGE_RLS_POLICY_MISSING = "FORGE_RLS_POLICY_MISSING" as const;
export const FORGE_RLS_TENANT_FIELD_MISSING =
  "FORGE_RLS_TENANT_FIELD_MISSING" as const;
export const FORGE_RLS_UNSUPPORTED_TENANT_TYPE =
  "FORGE_RLS_UNSUPPORTED_TENANT_TYPE" as const;
export const FORGE_RLS_FORCE_DISABLED = "FORGE_RLS_FORCE_DISABLED" as const;
export const FORGE_RLS_APPLY_FAILED = "FORGE_RLS_APPLY_FAILED" as const;
export const FORGE_RLS_TEST_FAILED = "FORGE_RLS_TEST_FAILED" as const;
export const FORGE_RLS_MUTATION_FAILED = "FORGE_RLS_MUTATION_FAILED" as const;
export const FORGE_RLS_SESSION_CONTEXT_MISSING =
  "FORGE_RLS_SESSION_CONTEXT_MISSING" as const;
export const FORGE_RLS_SESSION_CONTEXT_UNSAFE =
  "FORGE_RLS_SESSION_CONTEXT_UNSAFE" as const;
export const FORGE_DB_SUPERUSER_RUNTIME = "FORGE_DB_SUPERUSER_RUNTIME" as const;
export const FORGE_DB_BYPASSRLS_RUNTIME = "FORGE_DB_BYPASSRLS_RUNTIME" as const;
export const FORGE_RLS_PGLITE_NOT_AUTHORITATIVE =
  "FORGE_RLS_PGLITE_NOT_AUTHORITATIVE" as const;
export const FORGE_RLS_RAW_SQL_UNSCOPED = "FORGE_RLS_RAW_SQL_UNSCOPED" as const;
export const FORGE_DEPS_TARGET_NOT_FOUND = "FORGE_DEPS_TARGET_NOT_FOUND" as const;
export const FORGE_DEPS_UNSUPPORTED_PACKAGE_MANAGER =
  "FORGE_DEPS_UNSUPPORTED_PACKAGE_MANAGER" as const;
export const FORGE_DEPS_PACKAGE_NOT_INSTALLED =
  "FORGE_DEPS_PACKAGE_NOT_INSTALLED" as const;
export const FORGE_DEPS_TARGET_ANALYSIS_FAILED =
  "FORGE_DEPS_TARGET_ANALYSIS_FAILED" as const;
export const FORGE_DEPS_API_BREAKING_CHANGE =
  "FORGE_DEPS_API_BREAKING_CHANGE" as const;
export const FORGE_DEPS_REMOVED_EXPORT_USED =
  "FORGE_DEPS_REMOVED_EXPORT_USED" as const;
export const FORGE_DEPS_SIGNATURE_CHANGED_USED =
  "FORGE_DEPS_SIGNATURE_CHANGED_USED" as const;
export const FORGE_DEPS_RUNTIME_CONTEXT_CHANGED =
  "FORGE_DEPS_RUNTIME_CONTEXT_CHANGED" as const;
export const FORGE_DEPS_SECRET_ADDED = "FORGE_DEPS_SECRET_ADDED" as const;
export const FORGE_DEPS_CAPABILITY_ADDED = "FORGE_DEPS_CAPABILITY_ADDED" as const;
export const FORGE_DEPS_SECURITY_REGRESSION =
  "FORGE_DEPS_SECURITY_REGRESSION" as const;
export const FORGE_DEPS_PEER_DEPENDENCY_CONFLICT =
  "FORGE_DEPS_PEER_DEPENDENCY_CONFLICT" as const;
export const FORGE_DEPS_ENGINE_INCOMPATIBLE =
  "FORGE_DEPS_ENGINE_INCOMPATIBLE" as const;
export const FORGE_DEPS_APPLY_FAILED = "FORGE_DEPS_APPLY_FAILED" as const;
export const FORGE_DEPS_ROLLBACK_FAILED = "FORGE_DEPS_ROLLBACK_FAILED" as const;
export const FORGE_DEPS_LOCKFILE_DRIFT = "FORGE_DEPS_LOCKFILE_DRIFT" as const;
export const FORGE_DEPS_UNKNOWN_EXPORT = "FORGE_DEPS_UNKNOWN_EXPORT" as const;
export const FORGE_DEPS_RUNTIME_TYPE_MISMATCH =
  "FORGE_DEPS_RUNTIME_TYPE_MISMATCH" as const;
export const FORGE_RELEASE_DIRTY_WORKTREE =
  "FORGE_RELEASE_DIRTY_WORKTREE" as const;
export const FORGE_RELEASE_GENERATED_DRIFT =
  "FORGE_RELEASE_GENERATED_DRIFT" as const;
export const FORGE_RELEASE_ID_MISSING = "FORGE_RELEASE_ID_MISSING" as const;
export const FORGE_RELEASE_PACKAGE_PACK_FAILED =
  "FORGE_RELEASE_PACKAGE_PACK_FAILED" as const;
export const FORGE_RELEASE_NPM_DIST_TAG_STALE =
  "FORGE_RELEASE_NPM_DIST_TAG_STALE" as const;
export const FORGE_RELEASE_NPM_DIST_TAG_CHECK_FAILED =
  "FORGE_RELEASE_NPM_DIST_TAG_CHECK_FAILED" as const;
export const FORGE_SOURCEMAP_PUBLIC_EXPOSURE =
  "FORGE_SOURCEMAP_PUBLIC_EXPOSURE" as const;
export const FORGE_SOURCEMAP_UPLOAD_MISSING =
  "FORGE_SOURCEMAP_UPLOAD_MISSING" as const;
export const FORGE_SOURCEMAP_UPLOAD_FAILED =
  "FORGE_SOURCEMAP_UPLOAD_FAILED" as const;
export const FORGE_SOURCEMAP_SYMBOLICATION_FAILED =
  "FORGE_SOURCEMAP_SYMBOLICATION_FAILED" as const;
export const FORGE_RELEASE_ARTIFACT_MISSING =
  "FORGE_RELEASE_ARTIFACT_MISSING" as const;
export const FORGE_RELEASE_PROVIDER_CONFIG_MISSING =
  "FORGE_RELEASE_PROVIDER_CONFIG_MISSING" as const;
export const FORGE_LIVE_INVALIDATION_WRITE_FAILED =
  "FORGE_LIVE_INVALIDATION_WRITE_FAILED" as const;
export const FORGE_LIVE_INVALIDATION_MISSING =
  "FORGE_LIVE_INVALIDATION_MISSING" as const;
export const FORGE_LIVE_WAKEUP_FAILED = "FORGE_LIVE_WAKEUP_FAILED" as const;
export const FORGE_LIVE_POLL_LAG = "FORGE_LIVE_POLL_LAG" as const;
export const FORGE_LIVE_SUBSCRIPTION_LIMIT =
  "FORGE_LIVE_SUBSCRIPTION_LIMIT" as const;
export const FORGE_LIVE_SNAPSHOT_TOO_LARGE =
  "FORGE_LIVE_SNAPSHOT_TOO_LARGE" as const;
export const FORGE_LIVE_BACKPRESSURE_DROPPED_UPDATE =
  "FORGE_LIVE_BACKPRESSURE_DROPPED_UPDATE" as const;
export const FORGE_LIVE_RERUN_FAILED = "FORGE_LIVE_RERUN_FAILED" as const;
export const FORGE_LIVE_AUTH_EXPIRED = "FORGE_LIVE_AUTH_EXPIRED" as const;
export const FORGE_LIVE_RELEASE_CHANGED = "FORGE_LIVE_RELEASE_CHANGED" as const;
export const FORGE_LIVE_TRANSPORT_UNSUPPORTED =
  "FORGE_LIVE_TRANSPORT_UNSUPPORTED" as const;
export const FORGE_LIVE_RESUME_FAILED = "FORGE_LIVE_RESUME_FAILED" as const;
export const FORGE_LIVE_MULTI_RUNTIME_UNSAFE =
  "FORGE_LIVE_MULTI_RUNTIME_UNSAFE" as const;
export const FORGE_MAKE_TABLE_EXISTS = "FORGE_MAKE_TABLE_EXISTS" as const;
export const FORGE_MAKE_TENANTS_TABLE_MISSING =
  "FORGE_MAKE_TENANTS_TABLE_MISSING" as const;
export const FORGE_MAKE_SCHEMA_PATCH_UNSAFE =
  "FORGE_MAKE_SCHEMA_PATCH_UNSAFE" as const;
export const FORGE_MAKE_FIELD_INVALID = "FORGE_MAKE_FIELD_INVALID" as const;
export const FORGE_MAKE_FIELD_EXISTS = "FORGE_MAKE_FIELD_EXISTS" as const;
export const FORGE_MAKE_INVALID_DEFAULT = "FORGE_MAKE_INVALID_DEFAULT" as const;
export const FORGE_MAKE_MIGRATION_REQUIRED_FIELD_RISK =
  "FORGE_MAKE_MIGRATION_REQUIRED_FIELD_RISK" as const;
export const FORGE_MAKE_POLICY_EXISTS = "FORGE_MAKE_POLICY_EXISTS" as const;
export const FORGE_MAKE_POLICY_EMPTY_ROLES =
  "FORGE_MAKE_POLICY_EMPTY_ROLES" as const;
export const FORGE_MAKE_POLICY_NAME_INVALID =
  "FORGE_MAKE_POLICY_NAME_INVALID" as const;
export const FORGE_MAKE_COMMAND_POLICY_MISSING =
  "FORGE_MAKE_COMMAND_POLICY_MISSING" as const;
export const FORGE_MAKE_COMMAND_TABLE_MISSING =
  "FORGE_MAKE_COMMAND_TABLE_MISSING" as const;
export const FORGE_MAKE_COMMAND_EXISTS = "FORGE_MAKE_COMMAND_EXISTS" as const;
export const FORGE_MAKE_PATCH_UNSAFE = "FORGE_MAKE_PATCH_UNSAFE" as const;
export const FORGE_MAKE_FILE_EXISTS = "FORGE_MAKE_FILE_EXISTS" as const;
export const FORGE_MAKE_FILE_MISSING = "FORGE_MAKE_FILE_MISSING" as const;
export const FORGE_MAKE_SCHEMA_UNSUPPORTED_SHAPE =
  "FORGE_MAKE_SCHEMA_UNSUPPORTED_SHAPE" as const;
export const FORGE_MAKE_POLICY_UNSUPPORTED_SHAPE =
  "FORGE_MAKE_POLICY_UNSUPPORTED_SHAPE" as const;
export const FORGE_MAKE_VERIFY_FAILED = "FORGE_MAKE_VERIFY_FAILED" as const;
export const FORGE_FEATURE_TABLE_EXISTS = "FORGE_FEATURE_TABLE_EXISTS" as const;
export const FORGE_FEATURE_FIELD_EXISTS = "FORGE_FEATURE_FIELD_EXISTS" as const;
export const FORGE_FEATURE_POLICY_CONFLICT =
  "FORGE_FEATURE_POLICY_CONFLICT" as const;
export const FORGE_FEATURE_ENTRY_EXISTS = "FORGE_FEATURE_ENTRY_EXISTS" as const;
export const FORGE_FEATURE_ROUTE_CONFLICT =
  "FORGE_FEATURE_ROUTE_CONFLICT" as const;
export const FORGE_FEATURE_BLUEPRINT_INVALID =
  "FORGE_FEATURE_BLUEPRINT_INVALID" as const;
export const FORGE_FEATURE_ALREADY_APPLIED =
  "FORGE_FEATURE_ALREADY_APPLIED" as const;
export const FORGE_FEATURE_HASH_MISMATCH =
  "FORGE_FEATURE_HASH_MISMATCH" as const;
export const FORGE_REFACTOR_TARGET_NOT_FOUND =
  "FORGE_REFACTOR_TARGET_NOT_FOUND" as const;
export const FORGE_REFACTOR_TARGET_EXISTS =
  "FORGE_REFACTOR_TARGET_EXISTS" as const;
export const FORGE_REFACTOR_FIELD_NOT_FOUND =
  "FORGE_REFACTOR_FIELD_NOT_FOUND" as const;
export const FORGE_REFACTOR_FIELD_EXISTS =
  "FORGE_REFACTOR_FIELD_EXISTS" as const;
export const FORGE_REFACTOR_FIELD_USED_IN_INDEX =
  "FORGE_REFACTOR_FIELD_USED_IN_INDEX" as const;
export const FORGE_REFACTOR_AMBIGUOUS_REFERENCE =
  "FORGE_REFACTOR_AMBIGUOUS_REFERENCE" as const;
export const FORGE_REFACTOR_PATCH_UNSAFE =
  "FORGE_REFACTOR_PATCH_UNSAFE" as const;
export const FORGE_REFACTOR_PUBLIC_API_CHANGE =
  "FORGE_REFACTOR_PUBLIC_API_CHANGE" as const;
export const FORGE_REFACTOR_MIGRATION_REQUIRED =
  "FORGE_REFACTOR_MIGRATION_REQUIRED" as const;
export const FORGE_REFACTOR_HIGH_RISK =
  "FORGE_REFACTOR_HIGH_RISK" as const;
export const FORGE_REFACTOR_GENERATED_FILE_EDIT_BLOCKED =
  "FORGE_REFACTOR_GENERATED_FILE_EDIT_BLOCKED" as const;
export const FORGE_REFACTOR_VERIFY_FAILED =
  "FORGE_REFACTOR_VERIFY_FAILED" as const;
export const FORGE_REFACTOR_ROLLBACK_FAILED =
  "FORGE_REFACTOR_ROLLBACK_FAILED" as const;
export const FORGE_REFACTOR_CTX_NOT_AVAILABLE =
  "FORGE_REFACTOR_CTX_NOT_AVAILABLE" as const;
export const FORGE_REFACTOR_SECRET_IN_CLIENT =
  "FORGE_REFACTOR_SECRET_IN_CLIENT" as const;
export const FORGE_REFACTOR_FORBIDDEN_RUNTIME_CONTEXT =
  "FORGE_REFACTOR_FORBIDDEN_RUNTIME_CONTEXT" as const;
export const FORGE_IMPACT_NO_BASE = "FORGE_IMPACT_NO_BASE" as const;
export const FORGE_IMPACT_GIT_UNAVAILABLE =
  "FORGE_IMPACT_GIT_UNAVAILABLE" as const;
export const FORGE_IMPACT_UNKNOWN_FILE = "FORGE_IMPACT_UNKNOWN_FILE" as const;
export const FORGE_IMPACT_GENERATED_DRIFT =
  "FORGE_IMPACT_GENERATED_DRIFT" as const;
export const FORGE_TESTGRAPH_EMPTY = "FORGE_TESTGRAPH_EMPTY" as const;
export const FORGE_TESTGRAPH_AMBIGUOUS = "FORGE_TESTGRAPH_AMBIGUOUS" as const;
export const FORGE_TEST_NOT_FOUND = "FORGE_TEST_NOT_FOUND" as const;
export const FORGE_TEST_PLAN_EMPTY = "FORGE_TEST_PLAN_EMPTY" as const;
export const FORGE_TEST_RUN_FAILED = "FORGE_TEST_RUN_FAILED" as const;
export const FORGE_TEST_RUN_TIMEOUT = "FORGE_TEST_RUN_TIMEOUT" as const;
export const FORGE_TEST_COMMAND_RESOLUTION_FAILED =
  "FORGE_TEST_COMMAND_RESOLUTION_FAILED" as const;
export const FORGE_TEST_COST_EXCEEDED = "FORGE_TEST_COST_EXCEEDED" as const;
export const FORGE_TEST_DOCKER_REQUIRED = "FORGE_TEST_DOCKER_REQUIRED" as const;
export const FORGE_TEST_BROWSER_REQUIRED = "FORGE_TEST_BROWSER_REQUIRED" as const;
export const FORGE_VERIFY_CHANGED_INCOMPLETE =
  "FORGE_VERIFY_CHANGED_INCOMPLETE" as const;
export const FORGE_VERIFY_NO_TESTS_SELECTED =
  "FORGE_VERIFY_NO_TESTS_SELECTED" as const;
export const FORGE_VERIFY_SCRIPT_TIMEOUT =
  "FORGE_VERIFY_SCRIPT_TIMEOUT" as const;
export const FORGE_REPAIR_SOURCE_NOT_FOUND =
  "FORGE_REPAIR_SOURCE_NOT_FOUND" as const;
export const FORGE_REPAIR_UNKNOWN_FAILURE =
  "FORGE_REPAIR_UNKNOWN_FAILURE" as const;
export const FORGE_REPAIR_NO_RULE_MATCHED =
  "FORGE_REPAIR_NO_RULE_MATCHED" as const;
export const FORGE_REPAIR_LOW_CONFIDENCE =
  "FORGE_REPAIR_LOW_CONFIDENCE" as const;
export const FORGE_REPAIR_PLAN_FAILED = "FORGE_REPAIR_PLAN_FAILED" as const;
export const FORGE_REPAIR_APPLY_FAILED = "FORGE_REPAIR_APPLY_FAILED" as const;
export const FORGE_REPAIR_VERIFY_FAILED = "FORGE_REPAIR_VERIFY_FAILED" as const;
export const FORGE_REPAIR_ROLLBACK_FAILED =
  "FORGE_REPAIR_ROLLBACK_FAILED" as const;
export const FORGE_REPAIR_UNSAFE_AUTO_APPLY =
  "FORGE_REPAIR_UNSAFE_AUTO_APPLY" as const;
export const FORGE_REPAIR_NEEDS_MANUAL_REVIEW =
  "FORGE_REPAIR_NEEDS_MANUAL_REVIEW" as const;
export const FORGE_REPAIR_AMBIGUOUS_FIX =
  "FORGE_REPAIR_AMBIGUOUS_FIX" as const;
export const FORGE_AGENT_TARGET_UNKNOWN = "FORGE_AGENT_TARGET_UNKNOWN" as const;
export const FORGE_AGENT_EXPORT_FAILED = "FORGE_AGENT_EXPORT_FAILED" as const;
export const FORGE_AGENT_STALE_EXPORT = "FORGE_AGENT_STALE_EXPORT" as const;
export const FORGE_AGENT_MARKERS_MISSING =
  "FORGE_AGENT_MARKERS_MISSING" as const;
export const FORGE_AGENT_USER_SECTION_CONFLICT =
  "FORGE_AGENT_USER_SECTION_CONFLICT" as const;
export const FORGE_AGENT_SECRET_LEAK = "FORGE_AGENT_SECRET_LEAK" as const;
export const FORGE_AGENT_ADAPTER_INVALID =
  "FORGE_AGENT_ADAPTER_INVALID" as const;
export const FORGE_AGENT_TEMPLATE_RENDER_FAILED =
  "FORGE_AGENT_TEMPLATE_RENDER_FAILED" as const;
export const FORGE_AGENT_VERIFY_FAILED = "FORGE_AGENT_VERIFY_FAILED" as const;
export const FORGE_REVIEW_BLOCKING_FINDINGS =
  "FORGE_REVIEW_BLOCKING_FINDINGS" as const;
export const FORGE_REVIEW_HIGH_RISK = "FORGE_REVIEW_HIGH_RISK" as const;
export const FORGE_REVIEW_TEST_PLAN_MISSING =
  "FORGE_REVIEW_TEST_PLAN_MISSING" as const;
export const FORGE_REVIEW_UPGRADE_PLAN_MISSING =
  "FORGE_REVIEW_UPGRADE_PLAN_MISSING" as const;
export const FORGE_REVIEW_AGENT_CONTRACT_STALE =
  "FORGE_REVIEW_AGENT_CONTRACT_STALE" as const;
export const FORGE_REVIEW_FRONTEND_SERVER_IMPORT =
  "FORGE_REVIEW_FRONTEND_SERVER_IMPORT" as const;
export const FORGE_REVIEW_POLICY_WIDENED =
  "FORGE_REVIEW_POLICY_WIDENED" as const;
export const FORGE_REVIEW_SECRET_ENV_MISSING =
  "FORGE_REVIEW_SECRET_ENV_MISSING" as const;
export const FORGE_REVIEW_LIVEQUERY_TEST_MISSING =
  "FORGE_REVIEW_LIVEQUERY_TEST_MISSING" as const;
export const FORGE_REVIEW_DEPLOY_RISK = "FORGE_REVIEW_DEPLOY_RISK" as const;
export const FORGE_REVIEW_OUTPUT_FAILED =
  "FORGE_REVIEW_OUTPUT_FAILED" as const;
export const FORGE_REVIEW_UI_SMOKE_MISSING =
  "FORGE_REVIEW_UI_SMOKE_MISSING" as const;
export const FORGE_UI_PLAYWRIGHT_MISSING =
  "FORGE_UI_PLAYWRIGHT_MISSING" as const;
export const FORGE_UI_BROWSER_MISSING = "FORGE_UI_BROWSER_MISSING" as const;
export const FORGE_UI_SERVER_START_FAILED =
  "FORGE_UI_SERVER_START_FAILED" as const;
export const FORGE_UI_RUNTIME_UNREACHABLE =
  "FORGE_UI_RUNTIME_UNREACHABLE" as const;
export const FORGE_UI_WEB_UNREACHABLE = "FORGE_UI_WEB_UNREACHABLE" as const;
export const FORGE_UI_ROUTE_FAILED = "FORGE_UI_ROUTE_FAILED" as const;
export const FORGE_UI_SELECTOR_NOT_FOUND =
  "FORGE_UI_SELECTOR_NOT_FOUND" as const;
export const FORGE_UI_EXPECTATION_FAILED =
  "FORGE_UI_EXPECTATION_FAILED" as const;
export const FORGE_UI_LIVE_UPDATE_TIMEOUT =
  "FORGE_UI_LIVE_UPDATE_TIMEOUT" as const;
export const FORGE_UI_POLICY_ERROR_MISSING =
  "FORGE_UI_POLICY_ERROR_MISSING" as const;
export const FORGE_UI_TRACE_ID_MISSING =
  "FORGE_UI_TRACE_ID_MISSING" as const;
export const FORGE_UI_CONSOLE_ERROR = "FORGE_UI_CONSOLE_ERROR" as const;
export const FORGE_UI_NETWORK_ERROR = "FORGE_UI_NETWORK_ERROR" as const;
export const FORGE_UI_SCREENSHOT_FAILED =
  "FORGE_UI_SCREENSHOT_FAILED" as const;
export const FORGE_UI_TRACE_FAILED = "FORGE_UI_TRACE_FAILED" as const;
export const FORGE_UI_TESTID_MISSING = "FORGE_UI_TESTID_MISSING" as const;
export const FORGE_UI_AUTH_SETUP_FAILED =
  "FORGE_UI_AUTH_SETUP_FAILED" as const;
export const FORGE_OUTBOX_PROCESS_FAILED = "FORGE_OUTBOX_PROCESS_FAILED" as const;
export const FORGE_OUTBOX_NO_SUBSCRIPTIONS = "FORGE_OUTBOX_NO_SUBSCRIPTIONS" as const;
export const FORGE_OUTBOX_DELIVERY_NOT_FOUND = "FORGE_OUTBOX_DELIVERY_NOT_FOUND" as const;
export const FORGE_ACTION_EVENT_UNPARSEABLE = "FORGE_ACTION_EVENT_UNPARSEABLE" as const;
export const FORGE_WORKFLOW_UNKNOWN = "FORGE_WORKFLOW_UNKNOWN" as const;
export const FORGE_WORKFLOW_STEP_FAILED = "FORGE_WORKFLOW_STEP_FAILED" as const;
export const FORGE_WORKFLOW_STEP_DEAD = "FORGE_WORKFLOW_STEP_DEAD" as const;
export const FORGE_WORKFLOW_RUN_NOT_FOUND = "FORGE_WORKFLOW_RUN_NOT_FOUND" as const;
export const FORGE_WORKFLOW_DUPLICATE_RUN = "FORGE_WORKFLOW_DUPLICATE_RUN" as const;
export const FORGE_WORKFLOW_INVALID_TRIGGER = "FORGE_WORKFLOW_INVALID_TRIGGER" as const;
export const FORGE_WORKFLOW_INVALID_STEP = "FORGE_WORKFLOW_INVALID_STEP" as const;
export const FORGE_WORKFLOW_CANCELED = "FORGE_WORKFLOW_CANCELED" as const;
export const FORGE_TELEMETRY_SECRET_REDACTED =
  "FORGE_TELEMETRY_SECRET_REDACTED" as const;
export const FORGE_TELEMETRY_PAYLOAD_TRUNCATED =
  "FORGE_TELEMETRY_PAYLOAD_TRUNCATED" as const;
export const FORGE_TELEMETRY_SINK_FAILED = "FORGE_TELEMETRY_SINK_FAILED" as const;
export const FORGE_TELEMETRY_UNKNOWN_SINK = "FORGE_TELEMETRY_UNKNOWN_SINK" as const;
export const FORGE_WEBHOOK_SIGNATURE_INVALID =
  "FORGE_WEBHOOK_SIGNATURE_INVALID" as const;
export const FORGE_WEBHOOK_TIMESTAMP_INVALID =
  "FORGE_WEBHOOK_TIMESTAMP_INVALID" as const;
export const FORGE_WEBHOOK_REPLAY_DETECTED =
  "FORGE_WEBHOOK_REPLAY_DETECTED" as const;
export const FORGE_POLICY_DENIED = "FORGE_POLICY_DENIED" as const;
export const FORGE_POLICY_MISSING = "FORGE_POLICY_MISSING" as const;
export const FORGE_POLICY_UNKNOWN = "FORGE_POLICY_UNKNOWN" as const;
export const FORGE_POLICY_DUPLICATE = "FORGE_POLICY_DUPLICATE" as const;
export const FORGE_POLICY_ROLE_EMPTY = "FORGE_POLICY_ROLE_EMPTY" as const;
export const FORGE_TENANT_TABLE_WITHOUT_TENANT_ID =
  "FORGE_TENANT_TABLE_WITHOUT_TENANT_ID" as const;
export const FORGE_TENANT_SCOPE_VIOLATION = "FORGE_TENANT_SCOPE_VIOLATION" as const;
export const FORGE_SECRET_MISSING = "FORGE_SECRET_MISSING" as const;
export const FORGE_SECRET_FORBIDDEN_CONTEXT =
  "FORGE_SECRET_FORBIDDEN_CONTEXT" as const;
export const FORGE_SECRET_DIRECT_PROCESS_ENV =
  "FORGE_SECRET_DIRECT_PROCESS_ENV" as const;
export const FORGE_ENV_PUBLIC_SECRET = "FORGE_ENV_PUBLIC_SECRET" as const;
export const FORGE_ENV_UNKNOWN_REQUIRED = "FORGE_ENV_UNKNOWN_REQUIRED" as const;
export const FORGE_VERIFY_POLICY = "FORGE_VERIFY_POLICY" as const;
export const FORGE_AI_FORBIDDEN_CONTEXT = "FORGE_AI_FORBIDDEN_CONTEXT" as const;
export const FORGE_AI_PROVIDER_UNKNOWN = "FORGE_AI_PROVIDER_UNKNOWN" as const;
export const FORGE_AI_MODEL_MISSING = "FORGE_AI_MODEL_MISSING" as const;
export const FORGE_AI_SECRET_MISSING = "FORGE_AI_SECRET_MISSING" as const;
export const FORGE_AI_DYNAMIC_PROVIDER = "FORGE_AI_DYNAMIC_PROVIDER" as const;
export const FORGE_AI_GENERATION_FAILED = "FORGE_AI_GENERATION_FAILED" as const;
export const FORGE_AI_USAGE_UNAVAILABLE = "FORGE_AI_USAGE_UNAVAILABLE" as const;
export const FORGE_AI_REDTEAM_FAILED = "FORGE_AI_REDTEAM_FAILED" as const;
export const FORGE_QUERY_WRITE_FORBIDDEN = "FORGE_QUERY_WRITE_FORBIDDEN" as const;
export const FORGE_QUERY_EMIT_FORBIDDEN = "FORGE_QUERY_EMIT_FORBIDDEN" as const;
export const FORGE_QUERY_SECRET_FORBIDDEN = "FORGE_QUERY_SECRET_FORBIDDEN" as const;
export const FORGE_QUERY_AI_FORBIDDEN = "FORGE_QUERY_AI_FORBIDDEN" as const;
export const FORGE_QUERY_INTEGRATION_FORBIDDEN =
  "FORGE_QUERY_INTEGRATION_FORBIDDEN" as const;
export const FORGE_QUERY_NOT_FOUND = "FORGE_QUERY_NOT_FOUND" as const;
export const FORGE_QUERY_FAILED = "FORGE_QUERY_FAILED" as const;
export const FORGE_LIVEQUERY_WRITE_FORBIDDEN =
  "FORGE_LIVEQUERY_WRITE_FORBIDDEN" as const;
export const FORGE_LIVEQUERY_EMIT_FORBIDDEN =
  "FORGE_LIVEQUERY_EMIT_FORBIDDEN" as const;
export const FORGE_LIVEQUERY_SECRET_FORBIDDEN =
  "FORGE_LIVEQUERY_SECRET_FORBIDDEN" as const;
export const FORGE_LIVEQUERY_AI_FORBIDDEN =
  "FORGE_LIVEQUERY_AI_FORBIDDEN" as const;
export const FORGE_LIVEQUERY_INTEGRATION_FORBIDDEN =
  "FORGE_LIVEQUERY_INTEGRATION_FORBIDDEN" as const;
export const FORGE_LIVEQUERY_POLICY_DENIED =
  "FORGE_LIVEQUERY_POLICY_DENIED" as const;
export const FORGE_LIVEQUERY_UNKNOWN = "FORGE_LIVEQUERY_UNKNOWN" as const;
export const FORGE_LIVEQUERY_SUBSCRIPTION_FAILED =
  "FORGE_LIVEQUERY_SUBSCRIPTION_FAILED" as const;
export const FORGE_LIVEQUERY_RERUN_FAILED =
  "FORGE_LIVEQUERY_RERUN_FAILED" as const;

export const DIAGNOSTIC_CODES = [
  FORGE_DUP_SYMBOL,
  FORGE_DRIFT,
  FORGE_PKG_NO_TYPES,
  FORGE_GUARD_VIOLATION,
  FORGE_SANDBOX_LIMIT,
  FORGE_SECRET_LEAK,
  FORGE_AGENT_CONTRACT_SECRET_LEAK,
  FORGE_AUTH_MISSING_TOKEN,
  FORGE_AUTH_INVALID_TOKEN,
  FORGE_AUTH_INVALID_ISSUER,
  FORGE_AUTH_INVALID_AUDIENCE,
  FORGE_AUTH_TOKEN_EXPIRED,
  FORGE_AUTH_JWKS_FAILED,
  FORGE_AUTH_CLAIM_MISSING,
  FORGE_AUTH_CLAIM_INVALID,
  FORGE_AUTH_TENANT_MISSING,
  FORGE_AUTH_DEV_HEADERS_IN_PRODUCTION,
  FORGE_AUTH_MODE_INVALID,
  FORGE_AUTH_DISABLED,
  FORGE_ORPHANED_GENERATED_FILE,
  FORGE_SANDBOX_ABNORMAL,
  FORGE_DUP_RUNTIME_ENTRY,
  FORGE_RUNTIME_UNRESOLVABLE,
  FORGE_RUNTIME_NOT_FOUND,
  FORGE_RUNTIME_GUARD_BLOCKED,
  FORGE_RUNTIME_EXPORT_NAME_REQUIRED,
  FORGE_EXTERNAL_RUNTIME_NOT_FOUND,
  FORGE_EXTERNAL_RUNTIME_UNSUPPORTED,
  FORGE_EXTERNAL_RUNTIME_FAILED,
  FORGE_EXTERNAL_RUNTIME_BAD_RESPONSE,
  FORGE_DEV_SERVER_ERROR,
  FORGE_DEV_WATCH_FAILED,
  FORGE_DEV_INVOKE_FAILED,
  FORGE_DEV_DOCTOR_MISSING_ARTIFACT,
  FORGE_DEV_DB_RESET,
  FORGE_DB_CONNECT_FAILED,
  FORGE_DB_MIGRATION_FAILED,
  FORGE_DB_UNSUPPORTED_FIELD_TYPE,
  FORGE_DB_INVALID_SQL_PLAN,
  FORGE_DB_EMPTY_TIMESTAMP_LITERAL,
  FORGE_DB_TRANSACTION_FAILED,
  FORGE_DB_OUTBOX_WRITE_FAILED,
  FORGE_DB_ADAPTER_UNAVAILABLE,
  FORGE_PGLITE_STORE_ABORTED,
  FORGE_PGLITE_STORE_ACTIVE,
  FORGE_RLS_POLICY_MISSING,
  FORGE_RLS_TENANT_FIELD_MISSING,
  FORGE_RLS_UNSUPPORTED_TENANT_TYPE,
  FORGE_RLS_FORCE_DISABLED,
  FORGE_RLS_APPLY_FAILED,
  FORGE_RLS_TEST_FAILED,
  FORGE_RLS_MUTATION_FAILED,
  FORGE_RLS_SESSION_CONTEXT_MISSING,
  FORGE_RLS_SESSION_CONTEXT_UNSAFE,
  FORGE_DB_SUPERUSER_RUNTIME,
  FORGE_DB_BYPASSRLS_RUNTIME,
  FORGE_RLS_PGLITE_NOT_AUTHORITATIVE,
  FORGE_RLS_RAW_SQL_UNSCOPED,
  FORGE_DEPS_TARGET_NOT_FOUND,
  FORGE_DEPS_UNSUPPORTED_PACKAGE_MANAGER,
  FORGE_DEPS_PACKAGE_NOT_INSTALLED,
  FORGE_DEPS_TARGET_ANALYSIS_FAILED,
  FORGE_DEPS_API_BREAKING_CHANGE,
  FORGE_DEPS_REMOVED_EXPORT_USED,
  FORGE_DEPS_SIGNATURE_CHANGED_USED,
  FORGE_DEPS_RUNTIME_CONTEXT_CHANGED,
  FORGE_DEPS_SECRET_ADDED,
  FORGE_DEPS_CAPABILITY_ADDED,
  FORGE_DEPS_SECURITY_REGRESSION,
  FORGE_DEPS_PEER_DEPENDENCY_CONFLICT,
  FORGE_DEPS_ENGINE_INCOMPATIBLE,
  FORGE_DEPS_APPLY_FAILED,
  FORGE_DEPS_ROLLBACK_FAILED,
  FORGE_DEPS_LOCKFILE_DRIFT,
  FORGE_DEPS_UNKNOWN_EXPORT,
  FORGE_DEPS_RUNTIME_TYPE_MISMATCH,
  FORGE_RELEASE_DIRTY_WORKTREE,
  FORGE_RELEASE_GENERATED_DRIFT,
  FORGE_RELEASE_ID_MISSING,
  FORGE_RELEASE_PACKAGE_PACK_FAILED,
  FORGE_RELEASE_NPM_DIST_TAG_STALE,
  FORGE_RELEASE_NPM_DIST_TAG_CHECK_FAILED,
  FORGE_SOURCEMAP_PUBLIC_EXPOSURE,
  FORGE_SOURCEMAP_UPLOAD_MISSING,
  FORGE_SOURCEMAP_UPLOAD_FAILED,
  FORGE_SOURCEMAP_SYMBOLICATION_FAILED,
  FORGE_RELEASE_ARTIFACT_MISSING,
  FORGE_RELEASE_PROVIDER_CONFIG_MISSING,
  FORGE_LIVE_INVALIDATION_WRITE_FAILED,
  FORGE_LIVE_INVALIDATION_MISSING,
  FORGE_LIVE_WAKEUP_FAILED,
  FORGE_LIVE_POLL_LAG,
  FORGE_LIVE_SUBSCRIPTION_LIMIT,
  FORGE_LIVE_SNAPSHOT_TOO_LARGE,
  FORGE_LIVE_BACKPRESSURE_DROPPED_UPDATE,
  FORGE_LIVE_RERUN_FAILED,
  FORGE_LIVE_AUTH_EXPIRED,
  FORGE_LIVE_RELEASE_CHANGED,
  FORGE_LIVE_TRANSPORT_UNSUPPORTED,
  FORGE_LIVE_RESUME_FAILED,
  FORGE_LIVE_MULTI_RUNTIME_UNSAFE,
  FORGE_MAKE_TABLE_EXISTS,
  FORGE_MAKE_TENANTS_TABLE_MISSING,
  FORGE_MAKE_SCHEMA_PATCH_UNSAFE,
  FORGE_MAKE_FIELD_INVALID,
  FORGE_MAKE_FIELD_EXISTS,
  FORGE_MAKE_INVALID_DEFAULT,
  FORGE_MAKE_MIGRATION_REQUIRED_FIELD_RISK,
  FORGE_MAKE_POLICY_EXISTS,
  FORGE_MAKE_POLICY_EMPTY_ROLES,
  FORGE_MAKE_POLICY_NAME_INVALID,
  FORGE_MAKE_COMMAND_POLICY_MISSING,
  FORGE_MAKE_COMMAND_TABLE_MISSING,
  FORGE_MAKE_COMMAND_EXISTS,
  FORGE_MAKE_PATCH_UNSAFE,
  FORGE_MAKE_FILE_EXISTS,
  FORGE_MAKE_FILE_MISSING,
  FORGE_MAKE_SCHEMA_UNSUPPORTED_SHAPE,
  FORGE_MAKE_POLICY_UNSUPPORTED_SHAPE,
  FORGE_MAKE_VERIFY_FAILED,
  FORGE_FEATURE_TABLE_EXISTS,
  FORGE_FEATURE_FIELD_EXISTS,
  FORGE_FEATURE_POLICY_CONFLICT,
  FORGE_FEATURE_ENTRY_EXISTS,
  FORGE_FEATURE_ROUTE_CONFLICT,
  FORGE_FEATURE_BLUEPRINT_INVALID,
  FORGE_FEATURE_ALREADY_APPLIED,
  FORGE_FEATURE_HASH_MISMATCH,
  FORGE_REFACTOR_TARGET_NOT_FOUND,
  FORGE_REFACTOR_TARGET_EXISTS,
  FORGE_REFACTOR_FIELD_NOT_FOUND,
  FORGE_REFACTOR_FIELD_EXISTS,
  FORGE_REFACTOR_FIELD_USED_IN_INDEX,
  FORGE_REFACTOR_AMBIGUOUS_REFERENCE,
  FORGE_REFACTOR_PATCH_UNSAFE,
  FORGE_REFACTOR_PUBLIC_API_CHANGE,
  FORGE_REFACTOR_MIGRATION_REQUIRED,
  FORGE_REFACTOR_HIGH_RISK,
  FORGE_REFACTOR_GENERATED_FILE_EDIT_BLOCKED,
  FORGE_REFACTOR_VERIFY_FAILED,
  FORGE_REFACTOR_ROLLBACK_FAILED,
  FORGE_REFACTOR_CTX_NOT_AVAILABLE,
  FORGE_REFACTOR_SECRET_IN_CLIENT,
  FORGE_REFACTOR_FORBIDDEN_RUNTIME_CONTEXT,
  FORGE_IMPACT_NO_BASE,
  FORGE_IMPACT_GIT_UNAVAILABLE,
  FORGE_IMPACT_UNKNOWN_FILE,
  FORGE_IMPACT_GENERATED_DRIFT,
  FORGE_TESTGRAPH_EMPTY,
  FORGE_TESTGRAPH_AMBIGUOUS,
  FORGE_TEST_NOT_FOUND,
  FORGE_TEST_PLAN_EMPTY,
  FORGE_TEST_RUN_FAILED,
  FORGE_TEST_RUN_TIMEOUT,
  FORGE_TEST_COMMAND_RESOLUTION_FAILED,
  FORGE_TEST_COST_EXCEEDED,
  FORGE_TEST_DOCKER_REQUIRED,
  FORGE_TEST_BROWSER_REQUIRED,
  FORGE_VERIFY_CHANGED_INCOMPLETE,
  FORGE_VERIFY_NO_TESTS_SELECTED,
  FORGE_REPAIR_SOURCE_NOT_FOUND,
  FORGE_REPAIR_UNKNOWN_FAILURE,
  FORGE_REPAIR_NO_RULE_MATCHED,
  FORGE_REPAIR_LOW_CONFIDENCE,
  FORGE_REPAIR_PLAN_FAILED,
  FORGE_REPAIR_APPLY_FAILED,
  FORGE_REPAIR_VERIFY_FAILED,
  FORGE_REPAIR_ROLLBACK_FAILED,
  FORGE_REPAIR_UNSAFE_AUTO_APPLY,
  FORGE_REPAIR_NEEDS_MANUAL_REVIEW,
  FORGE_REPAIR_AMBIGUOUS_FIX,
  FORGE_AGENT_TARGET_UNKNOWN,
  FORGE_AGENT_EXPORT_FAILED,
  FORGE_AGENT_STALE_EXPORT,
  FORGE_AGENT_MARKERS_MISSING,
  FORGE_AGENT_USER_SECTION_CONFLICT,
  FORGE_AGENT_SECRET_LEAK,
  FORGE_AGENT_ADAPTER_INVALID,
  FORGE_AGENT_TEMPLATE_RENDER_FAILED,
  FORGE_AGENT_VERIFY_FAILED,
  FORGE_REVIEW_BLOCKING_FINDINGS,
  FORGE_REVIEW_HIGH_RISK,
  FORGE_REVIEW_TEST_PLAN_MISSING,
  FORGE_REVIEW_UPGRADE_PLAN_MISSING,
  FORGE_REVIEW_AGENT_CONTRACT_STALE,
  FORGE_REVIEW_FRONTEND_SERVER_IMPORT,
  FORGE_REVIEW_POLICY_WIDENED,
  FORGE_REVIEW_SECRET_ENV_MISSING,
  FORGE_REVIEW_LIVEQUERY_TEST_MISSING,
  FORGE_REVIEW_DEPLOY_RISK,
  FORGE_REVIEW_OUTPUT_FAILED,
  FORGE_REVIEW_UI_SMOKE_MISSING,
  FORGE_UI_PLAYWRIGHT_MISSING,
  FORGE_UI_BROWSER_MISSING,
  FORGE_UI_SERVER_START_FAILED,
  FORGE_UI_RUNTIME_UNREACHABLE,
  FORGE_UI_WEB_UNREACHABLE,
  FORGE_UI_ROUTE_FAILED,
  FORGE_UI_SELECTOR_NOT_FOUND,
  FORGE_UI_EXPECTATION_FAILED,
  FORGE_UI_LIVE_UPDATE_TIMEOUT,
  FORGE_UI_POLICY_ERROR_MISSING,
  FORGE_UI_TRACE_ID_MISSING,
  FORGE_UI_CONSOLE_ERROR,
  FORGE_UI_NETWORK_ERROR,
  FORGE_UI_SCREENSHOT_FAILED,
  FORGE_UI_TRACE_FAILED,
  FORGE_UI_TESTID_MISSING,
  FORGE_UI_AUTH_SETUP_FAILED,
  FORGE_OUTBOX_PROCESS_FAILED,
  FORGE_OUTBOX_NO_SUBSCRIPTIONS,
  FORGE_OUTBOX_DELIVERY_NOT_FOUND,
  FORGE_ACTION_EVENT_UNPARSEABLE,
  FORGE_WORKFLOW_UNKNOWN,
  FORGE_WORKFLOW_STEP_FAILED,
  FORGE_WORKFLOW_STEP_DEAD,
  FORGE_WORKFLOW_RUN_NOT_FOUND,
  FORGE_WORKFLOW_DUPLICATE_RUN,
  FORGE_WORKFLOW_INVALID_TRIGGER,
  FORGE_WORKFLOW_INVALID_STEP,
  FORGE_WORKFLOW_CANCELED,
  FORGE_TELEMETRY_SECRET_REDACTED,
  FORGE_TELEMETRY_PAYLOAD_TRUNCATED,
  FORGE_TELEMETRY_SINK_FAILED,
  FORGE_TELEMETRY_UNKNOWN_SINK,
  FORGE_WEBHOOK_SIGNATURE_INVALID,
  FORGE_WEBHOOK_TIMESTAMP_INVALID,
  FORGE_WEBHOOK_REPLAY_DETECTED,
  FORGE_POLICY_DENIED,
  FORGE_POLICY_MISSING,
  FORGE_POLICY_UNKNOWN,
  FORGE_POLICY_DUPLICATE,
  FORGE_POLICY_ROLE_EMPTY,
  FORGE_TENANT_TABLE_WITHOUT_TENANT_ID,
  FORGE_TENANT_SCOPE_VIOLATION,
  FORGE_SECRET_MISSING,
  FORGE_SECRET_FORBIDDEN_CONTEXT,
  FORGE_SECRET_DIRECT_PROCESS_ENV,
  FORGE_ENV_PUBLIC_SECRET,
  FORGE_ENV_UNKNOWN_REQUIRED,
  FORGE_VERIFY_POLICY,
  FORGE_AI_FORBIDDEN_CONTEXT,
  FORGE_AI_PROVIDER_UNKNOWN,
  FORGE_AI_MODEL_MISSING,
  FORGE_AI_SECRET_MISSING,
  FORGE_AI_DYNAMIC_PROVIDER,
  FORGE_AI_GENERATION_FAILED,
  FORGE_AI_USAGE_UNAVAILABLE,
  FORGE_AI_REDTEAM_FAILED,
  FORGE_QUERY_WRITE_FORBIDDEN,
  FORGE_QUERY_EMIT_FORBIDDEN,
  FORGE_QUERY_SECRET_FORBIDDEN,
  FORGE_QUERY_AI_FORBIDDEN,
  FORGE_QUERY_INTEGRATION_FORBIDDEN,
  FORGE_QUERY_NOT_FOUND,
  FORGE_QUERY_FAILED,
  FORGE_LIVEQUERY_WRITE_FORBIDDEN,
  FORGE_LIVEQUERY_EMIT_FORBIDDEN,
  FORGE_LIVEQUERY_SECRET_FORBIDDEN,
  FORGE_LIVEQUERY_AI_FORBIDDEN,
  FORGE_LIVEQUERY_INTEGRATION_FORBIDDEN,
  FORGE_LIVEQUERY_POLICY_DENIED,
  FORGE_LIVEQUERY_UNKNOWN,
  FORGE_LIVEQUERY_SUBSCRIPTION_FAILED,
  FORGE_LIVEQUERY_RERUN_FAILED,
] as const;

export type DiagnosticCode = (typeof DIAGNOSTIC_CODES)[number];
