export const FORGE_DUP_SYMBOL = "FORGE_DUP_SYMBOL" as const;
export const FORGE_DRIFT = "FORGE_DRIFT" as const;
export const FORGE_PKG_NO_TYPES = "FORGE_PKG_NO_TYPES" as const;
export const FORGE_GUARD_VIOLATION = "FORGE_GUARD_VIOLATION" as const;
export const FORGE_SANDBOX_LIMIT = "FORGE_SANDBOX_LIMIT" as const;
export const FORGE_SECRET_LEAK = "FORGE_SECRET_LEAK" as const;
export const FORGE_ORPHANED_GENERATED_FILE =
  "FORGE_ORPHANED_GENERATED_FILE" as const;
export const FORGE_SANDBOX_ABNORMAL = "FORGE_SANDBOX_ABNORMAL" as const;
export const FORGE_DUP_RUNTIME_ENTRY = "FORGE_DUP_RUNTIME_ENTRY" as const;
export const FORGE_RUNTIME_UNRESOLVABLE = "FORGE_RUNTIME_UNRESOLVABLE" as const;
export const FORGE_RUNTIME_NOT_FOUND = "FORGE_RUNTIME_NOT_FOUND" as const;
export const FORGE_RUNTIME_GUARD_BLOCKED = "FORGE_RUNTIME_GUARD_BLOCKED" as const;

export const DIAGNOSTIC_CODES = [
  FORGE_DUP_SYMBOL,
  FORGE_DRIFT,
  FORGE_PKG_NO_TYPES,
  FORGE_GUARD_VIOLATION,
  FORGE_SANDBOX_LIMIT,
  FORGE_SECRET_LEAK,
  FORGE_ORPHANED_GENERATED_FILE,
  FORGE_SANDBOX_ABNORMAL,
  FORGE_DUP_RUNTIME_ENTRY,
  FORGE_RUNTIME_UNRESOLVABLE,
  FORGE_RUNTIME_NOT_FOUND,
  FORGE_RUNTIME_GUARD_BLOCKED,
] as const;

export type DiagnosticCode = (typeof DIAGNOSTIC_CODES)[number];
